### ISSUE TITLE
Windows Tray Icon stays black

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#1014]
_Super Productivity 6.5.2 on Windows 10_

Super Productivity tray icon is black on black (and doesn't change even if I change Windows to dark mode):
![Screenshot 2021-04-01 104858](https://user-images.githubusercontent.com/64837252/113273025-8498d100-92dc-11eb-9542-08d0991fc55d.png)

I just learned today that it should look different, though. Is there anything in the settings that I may have missed or is this a bug? :)

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting this! This is a bug and might be a good issue for people being new to the project.

**Comment by DenysMb** [comment]
In the code, the variable `shoudUseDarkColors` in the **indicator.ts** file is equals to: `forceDarkTray || nativeTheme.shouldUseDarkColors`.

First, at least in Linux, the `forceDarkTray`, in **main.ts**, is never changed because the `val` in `process.argv.forEach((val) => {..}` never includes `'--force-dark-tray'`

Second, the **shouldUseDarkColors** not exist in the **nativeTheme**. The **nativeTheme** only contains the keys: **_events, _eventsCount** ad **_maxListeners**.

To make it use the light version of the tray icon I had to manually change the `shouldUseDarkColors` to **true**

I don't know how to solve it, so I cannot make a fix and a merge request, but If it would be more complicated then it seems, a simple temporary solution will be to make a icon with a blue circle background, like the logo.

**Comment by johannesjo** [comment]
Hey there! I just updated the electron version to 12. Not sure, but this might fix the issue for windows, even though I didn't find anything in the changelogs. 

It's also possible to work around this issue by adding the `--force-dark-tray` flag when starting the app, but that is not very user friendly I have to admit.

**Comment by schlauerlauer** [comment]
In gnome the white version should be default no matter the theme, because the top bar is always dark.

With the Adwaita-dark theme it shows the correct icon.

This is with the default gnome theme (you can only see it when you hover over it):

![superprod_gnome](https://user-images.githubusercontent.com/40915271/118931037-c9d59880-b946-11eb-86df-95cc86d21cd8.jpg)

To be fair you have to install an extension to see the icon tray in the first place.

**Comment by trallnag** [comment]
This is still relevant. I was about to create a new issue

![image](https://user-images.githubusercontent.com/24834206/157231616-5264a2bf-1137-4972-a126-2e7abecf225a.png)

**Comment by rklec** [comment]
The issue is still there.

**Comment by zoli** [comment]
I would like to take on this.

**Comment by zoli** [comment]
After checking the code, I think the problem is OS specific even OS version specific for windows. 
What I found in linux systems for at least i3 (which I use myself), Gnome, Ubuntu the problem is that the status bar background is dark no matter the theme is light or dark, So I think the default should be to use dark colors (tray icon with white color) for those.
I don't use windows but from what I have seen in youtube for windows 11 the code works fine because the taskbar background color changes regarding to system theme, but for windows 10 (as @halloichbingunnar pointed) the taskbar is always dark and it should be same as linux I think.
Also for mac which I don't use that to I think the code works fine and there is no need to any change.

So my suggestion would be to change set `shouldUseDarkColors` to `true` for windows 10 and linux systems.

If its OK by you @johannesjo I will go and create a PR for it.

**Comment by johannesjo** [comment]
@zoli ! Makes sense to me! Thank you!

**Comment by saintech** [comment]
The issue is still there.

<img width="352" height="72" alt="Image" src="https://github.com/user-attachments/assets/cc0f019b-3b22-4369-ba9c-0610675d9920" />

* Version used: ~14.0.5~ 14.3.2
* Operating System and version: Windows 11 24H2 Build 26100.4652

Installed via `scoop`.
