### ISSUE TITLE
[Feature Request] Create issue in Jira (from within SP)

### ISSUE THREAD

**Issue by stuartro** [johannesjo/super-productivity#114]
When creating a new task (within SP) it would be great if there was an option to create a new story in Jira. I understand this is probably a long-shot, as it's likely a non-trivial exercise to create an issue in Jira programmatically, but it sure would be nice. 

Thank you for a superb tool. Could easily be called "superb-productivity" :-).

**Comment by johannesjo** [comment]
I'm glad that you like the app :)

This will be indeed a little tricky, due to the many different options and fields Jira provides, which can be different for every instance. For me - at least when dealing with jira projects - the app is more a tool to plan my current task at hand and less to plan the overall project, as this is usually done in meetings with other people. Don't know. Have to think about it.
