### ISSUE TITLE
Today counter counts completed tasks

### ISSUE THREAD

**Issue by cohalex** [johannesjo/super-productivity#1186]
The "Today" counter on the left sidebar counts tasks tagged with "Today" but I would expect it to count only **active** tasks tagged with "Today", not completed ones. Currently I need to manually remove the "Today" tag from every completed task.

**Comment by johannesjo** [comment]
Thanks for opening this up. Makes sense to change it from a user perspective.

**Comment by JoseOlin** [comment]
Just adding my two cents

If 3 tasks out of 9 scheduled  have been completed, it could show 3/9 instead of just 9.

Or 3, 6 (3 finished, 6 to be done)

**Comment by JoseOlin** [comment]
Still relevant, I think.

I'm actually thinking of working on this, is there a guide where you explain the general structure of the code @johannesjo ? I know maybe this is asking too much, but for a long time I stopped asking for a guide of your personal use of super productivity and it turned out that you had already done one, so I ask just in case it already exists.

**Comment by johannesjo** [comment]
Hey @JoseOlin apart from the comments in the code itself there is no documentation unfortunately. :/

**Comment by JoseOlin** [comment]
Still relevant

What sections of the code would you recommend reading thoroughly in order to try adding this functionality?

**Comment by steve-biggs** [comment]
Bump! This is an issue for me too. @JoseOlin suggestion of 3 / 9 or similar is a good idea IMO.

**Comment by JoseOlin** [comment]
> Bump! This is an issue for me too. @JoseOlin suggestion of 3 / 9 or similar is a good idea IMO.

Yep @steve-biggs, and one that is apparently relatively easy to implement, since projects already have that behavior. Perhaps an option can be added to the settings in a future version.

@johannesjo, could you help me by telling me how and in what section of the code the counter that appears as the Today icon in the sidebar is calculated?
I did a code read and I can find the list of projects and tags, the Timeline and Scheduled, but not the counter for Today (it's the T component right?)


Understanding this, I could try adding an option in Settings to choose the format of the Today counter.

**Comment by johannesjo** [comment]
https://github.com/johannesjo/super-productivity/blob/bec40c57e5b8e96b68d6eaf5c2f50cd791d8af28/src/app/core-ui/side-nav/side-nav.component.html#L18
