### ISSUE TITLE
There is a link in the app to update the version to 2.0?

### ISSUE THREAD

**Issue by matcabgomes** [johannesjo/super-productivity#130]
Hi there, congrats for the good work!

There is a link in the app to update the version to 2.0? Or it has to be 'updated' only by downloading again? I'm currently on v1.10.52 rs, I'm kind of outdated but it's because it worked very well for me on this version. I'm looking forward to user the 2.0!

**Comment by cobbinaloic** [comment]
Well, my OS (MXlinux) automatically updated to V2. At first I was so excited but it felt so buggy that I had to rush back to 1.10.56. I've been so busy with work, I've not have enough time to report those bugs. Maybe in the weekend

**Comment by johannesjo** [comment]
@marcabgomes It should be updated automatically. You only need to choose importing the v1 data. Take care to download v2.0.1 first, as v2.0.0 has some issue with importing the tasks.

@cobbinaloic sorry to hear that you encounterd so many issues.  The release was a little rushed in the end after working on it for almost half a year and I accidently put it v.1.1999.1000 for automatic updates which is not at all what I wanted. Some of the issues should be fixed with v2.0.1.

I will improve the release strategy and work with snaps edge channel from now on and release to stable only every now and then. Moving away from bintray deb releases (which caused a lot of trouble) this should be manageable without losing too much time for development.


Bug reports would be very welcome indeed!
