### ISSUE TITLE
Improved Caldav integration

### ISSUE THREAD

**Issue by memen45** [johannesjo/super-productivity#1312]
## Problem Statement
Some issues I encounter when using this with CalDav integration:
#### 1. setup complete integration settings for each project
![image](https://user-images.githubusercontent.com/27782135/122784635-f157b200-d2b2-11eb-922d-46279757b7fd.png)
In Nextcloud I have multiple calendars to group certain tasks together (e.g. personal, study, side-business, etc). Now I would like to make a project for each of those, and now for each new project I have to completely fill out the url, user and password again. 
#### 2. syncing of new tasks added by SP
![image](https://user-images.githubusercontent.com/27782135/122784858-219f5080-d2b3-11eb-8271-cb7eb33a2e20.png)
With Caldav integration setup, I expected 'Add task' to create a task in the Caldav backend as well, but currently it only creates a task inside the SP project. Additionally, when editing a task from CalDav, it remains in SP and is not synced to CalDav at any time.
#### 3. scheduled tasks not in calendar
![image](https://user-images.githubusercontent.com/27782135/122785250-8490e780-d2b3-11eb-86d7-435823f23bfe.png)
When a task is scheduled for a certain time slot, this is not reflected in the corresponding calendar. I would expect that if a task from calendar X is scheduled, a calendar event is scheduled for calendar X for this time period. However, nothing shows up in the CalDav calendar events.

#### 1. default integration settings in main settings
Maybe it is possible to add a 'default' CalDav integration backend in the main settings page. For 'Create Project' -> 'Setup CalDav Integration' the list of available calendars could be shown, with optionally an 'add CalDav integration' option to add a different account or calendar from different domain.
When using Nextcloud, it should be possible to derive the CalDav urls from the sync settings as well, so in theory, only the Nextcloud login details have to be provided and the app should be able to find webdav urls and CalDav urls automatically.

#### 2. sync added tasks and deleted tasks as well
Tasks added or deleted (or edited), should be updated to the CalDav integration if setup.
#### 3. create/update/remove calendar events for scheduled tasks
Tasks create a calendar event when scheduled. This calendar event is updated accordingly when task schedule changes, or is unscheduled/removed.

**Comment by johannesjo** [comment]
Thank you very much for opening this up. Makes sense to me to go for a deeper integration. If somebody wants to tackle this, I am accepting PRs (though we also should have a more detailed discussion for the implementation starts)..

**Comment by Petemir** [comment]
> This issue has not received any updates in 90 days. Please comment, if this still relevant!

I think it is! :)

**Comment by mrmotallebi** [comment]
Other than the 3 points posted by OP, I would like to add the following which are mainly around time tracking:

**4. Reflect time estimate and time spent in status of CalDAV task, start date and progress percentage** 

When a task in SP is first started, update the status in CalDAV and its start date (if not previously set). If a time estimate is set in SP, update the percentage progress each time in CalDAV based on time spent on it.

**5. Add a note or attachment of the time log to CalDAV.**

This is probably not in the CalDAV spec but it would be good to attach the time log (in some custom format) to each task, or append it to the notes of that task.

**Comment by TheModernWizard** [comment]
Still relevant!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/johannesjo/super-productivity/issues/1312#issuecomment-1747912688

@Github-Actions, it's relevant. Lots of people just subscribe to issue closure.

**Comment by madpipeline** [comment]
I'd like to pledge 20€ to get this functionality working.

**Comment by johannesjo** [comment]
FYI for some people the improved iCal calendar integration in v8.0.0 might be worth a look as alternative.

**Comment by ju6ge** [comment]
Hi I am checking out SP right now, and am hitting this issue, I am on version 8.0.1 and the iCal calender integration is not an alternative. For one thing it is not possible to configure a username and password there, as in the CalDav integration. 

In my Option not having two way sync for CalDav is a dealbreaker to using SP. The reason is pretty simple without two sync it is not interoperable with other tools that use the `vTodo` Spec. So I can either throw away my existing workflows and move everything to SP or just not use SP, which is very sad, because it would be a great tool because of its the other integrations (Gitlab, Github which are fine to be pull only). This is annoying because it means I can not have tasks list that sync with CalDav and are shared with other people.

**Comment by johannesjo** [comment]
PRs dealing with this are welcome :) I don't even use the Caldav integration myself, so I am not the right person for the job.

**Comment by ju6ge** [comment]
@johannesjo I get that you have a lot to and are not able to test this issue since you are not using CalDav. But since you are the author of SP would it be to much to ask some for a bit more detailed response here? 

What i mean by that asking for PR is all well and good. But lets assume somebody is new to SP is a typescript dev and want to contribute. It is a hell of an effort to figure out what parts of the code base need to be touched to make it happen. So it would be great if you could write down your thoughts on this?

- Do Integrations in there current form even support receiving new/updated tasks?
- If yes? What functions would need to be added to the `calendar-integration`?

There is probably a lot more specific things that might need adjustment to make it happen. 

Having something like that would at the very least lower the bar to somebody else implementing it, by giving them a head start in where to search the code base for answers.

**Comment by johannesjo** [comment]
All (or at least most) the relevant code can be found here:
https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers/caldav

Updating tasks is already present for the jira integration. So having a look there might be helpful.
https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers

> If yes? What functions would need to be added to the calendar-integration?

Calendar integration and cal dav are two different things at this point, since the caldav protocol is not supported everywhere. 

It's a very broad question. Not sure how to answer it without going into much detail. To be perfectly honest: This might not be the ideal task for someone being new Typescript and all the surrounding technologies. Doable if you're willing to learn and spent some time, but one would need to put some effort into it.
