### ISSUE TITLE
Timeline section improvements

### ISSUE THREAD

**Issue by JoseOlin** [johannesjo/super-productivity#1381]
## Problem Statement

The timeline section is promising as a scheduling alternative to normal calendars, however it has certain behaviors that have not allowed to be entirely useful to me. I list them below:

- A **drag-and-drop schedule would be ideal** in this section, with lines for hours, which are collapsed by default and expand when you drop tasks in that section, which should automatically modify the scheduled time for the task. 

- The **section shows non-scheduled subtasks**, which are sisters of  scheduled subtasks. This is, if you scheduled a subtask, every subtask of the parent is added to the Timeline. I don't think this is a desirable behavior.
   + **Expected behavior**: Only scheduled subtasks should appear in this section.

 ## :grey_question: Possible Solution

- As alternative to drag and drop, instead of having the same shortcuts as the Today section (Start tracking, Set as done and Show additional info) **it should have its own scheduling-oriented shortcuts**, (for example Schedule time and Time).

**Comment by johannesjo** [comment]
Thank you very much for opening this up. I also would love to see drag and drop to work here (though it#s a bit complicated to determine what should happen for all the different possible cases here).

**Comment by JoseOlin** [comment]
This is solved in the last versions! :D :dancers:

**Comment by JoseOlin** [comment]
Oh, I just recheck and the drag and drop behavior has been implemented with the up and down arrows (which I consider effective enough), but the **unscheduled subtasks still appear in the section**.

Is it possible to reopen this issue or is there a similar one for this functionality?

**Comment by johannesjo** [comment]
Could you maybe outline how you would expect the following scenarios show up:

1. Parent task is scheduled, but no sub task is scheduled
2. Parent task is scheduled and a sub task is scheduled 

Also I am afraid, that this might be hard to implement and would have the side effect that the today list and the timeline would not be in sync anymore and we would need a complete different list for the timeline. Currently the timeline just uses the same order, which makes sense, since many people order their task by priority anyway. So I am open for implementing this optionally, but probably won't work on this myself, as I prefer the lists to be in sync.

**Comment by JoseOlin** [comment]
Hi!

I think I am beginning to understand the proposed use of the Timeline section, in addition to a calendar it is a kind of buffer with some probable subtasks to add to Today section, right?

In that case, I think [adding a Toggle sub task visivility level in Today's section](https://github.com/johannesjo/super-productivity/issues/1740)  should be enough, and in Timeline I would only modify that the unscheduled substask appear after the scheduled ones, probably adding a slight split between scheduled and non-scheduled subtasks.


Confirming current behavior:
If you schedule a parent task **with** subtasks, **all its subtasks are added** to the Timeline, but **not the main task**.
Only **scheduled parent tasks without subtasks** are added to the Timeline.

Right? 

Thanks in advance.

**Comment by johannesjo** [comment]
That's an interesting suggestion. It would be ideal if those tasks also wouldn't be taken into consideration for the total estimate calculation, but as a first step it might we worth to test just hiding them.

> If you schedule a parent task **with** subtasks, **all its subtasks are added** to the Timeline, but **not the main task**.

Yes! This is because the different lists (for porjects, tags and today) only contain parent tasks. While it would have some advantages to change this, it also would make the app more complicated to use (and more more prone to introducing errors).

**Comment by yujiangwang** [comment]
Hi, I have been trying out this app for a few weeks now and absolutely love it. There is just one thing in the timeline that keeps bothering me, which I am not sure if it belongs here, but here you go. I have my Google calendar integrated with the timeline, but it is currently also showing deleted events from my calendar (e.g. recurring meetings, where I deleted one or two instances over xmas). Is that a bug, or is there an obvious fix that I missed? Thanks in advance!
