### ISSUE TITLE
Android widget dark mode

### ISSUE THREAD

**Issue by njakes** [johannesjo/super-productivity#1439]
## Problem Statement
Your app just keeps getting better and better keep up the good work. I'm opening the feature request to see if the android widget can have a dark mode option. 

## :grey_question: Possible Solution
Sorry, i have no experience in this matter.

## :arrow_heading_up: Describe alternatives you've considered
An alternative could be decreasing the opacity of the white background.

**Comment by reinhart1010** [comment]
Ah, didn't notice that there's a task widget already for the native Android app. This should be an easy fix, modifying the `app/src/main/res/layout/task_list_widget.xml` and `app/src/main/res/java/com/superproductivity/superproductivity/TaskListWidget.java`.

However, since native dark mode support in Android is still limited (Android 10 or newer, and hopefully some hacks to make it work in Samsung's Android 9 devices). As of now Google recommends three options for theme settings in Android apps:

+ Light
+ Dark
+ Auto (Follow System Settings)

as well as (for Android 9 and below):

+ Light
+ Dark
+ Set by Battery Saver

Since we implement the dark mode settings as a switch, should there be a dedicated option to set the theme for the widget?

**Comment by johannesjo** [comment]
Thank you very much @reinhart1010 ! A setting for the widget makes sense, though I would also be fine with just using the the light or dark setting provided for the app itself.

**Comment by reinhart1010** [comment]
I might want to work with this, but still don't know how to pass the configuration (everything saved into Settings) into the Android widget.

**Comment by johannesjo** [comment]
> I might want to work with this, but still don't know how to pass the configuration (everything saved into Settings) into the Android widget.

The data needs to be send from the app weblayer to the android layer somehow (and be persisted there until being updated again). Something like this is already done for the automatic backups (exposed as saveToDb via the webview JavaScriptInterface). Please let me know if you need help with something in particular.
