### ISSUE TITLE
Also import jira subtask for jira issues

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#150]
## Your Environment
* Version used: 2.2.2 deb
* Operating System and version: Ubuntu 18.10
* Desktop Environment: xfce - xubuntu

## Expected Behavior
When I have subtasks in jira, I'd like to see them in sp too.

## Current Behavior
Just the task is shown, not the subtasks with it. They are separate tasks to be selected.

## Steps to Reproduce (for bugs)
1. create issue/task in jira
2. create subtask in jira
3. add task in sp

**Comment by johannesjo** [comment]
This is a little bit more complicated. Currently the app assumes that you import the sub tasks themselves to break them further down by yourself. Things like the worklog submission and the issue transitioning would have to account for that. Might be something for later on, but for now, I would focus on making the Jira Integration and other parts of the app more stable.

**Comment by jeensg** [comment]
Sounds reasonable :-)

**Comment by theCalcaholic** [comment]
Hm, if you configure your JQL query accordingly, this should 'just work' (at least it does for me).

You have to import sub tasks explicitly, but they are correctly integrated once imported.

**Comment by johannesjo** [comment]
As I understood the question @jeensg expected the jira sub task to be imported as sub tasks when importing the parent task which AFAIK is not possible atm.

Doesn't seem that there is a huge demand for this feature and as I don't need it myself, I will close this for now.  If more people need it we can reopen the issue of course.

**Comment by ToNyRANDRIAMANANTSOA** [comment]
Hello, I am facing the exact same situation right now. I took some time to detail each tasks in the jira backlog with subtasks. Then from SP, only the parent tasks were imported.
I'm not sure how can I achieve importing the each corresponding subtasks of each imported jira tasks though via JQL as @theCalcaholic suggested.
Is there any workaround available to avoid re adding all of them manually in SP ?
Thank you.

**Comment by kj4ezj** [comment]
It has been five years since this issue was closed, can we please reopen and revisit this feature request @johannesjo? Open [issue 6364](https://github.com/super-productivity/super-productivity/issues/6364) is asking for the exact same functionality as this, but for GitHub. Perhaps they should be combined or a new issue opened to solve this issue generically. I can also open a new issue for this instead of resurrecting this one, if you'd prefer. However you want to proceed.

I need this functionality and I am willing to contribute my time towards implementing it.

There _must_ be a very large number of Super Productivity users who also need this functionality, whether represented here or not. Jira is used by >300k enterprises worldwide and is the de-facto standard for managing large software engineering projects, for better or worse. Anyone seriously using Super Productivity with Jira in an Agile/Scrum/Kanban environment where work is decomposed by initiative > epic > story > subtask will encounter this need.

Open [issue 4821](https://github.com/super-productivity/super-productivity/issues/4821) is also tangentially relevant, as Jira [expects](https://community.atlassian.com/forums/Jira-questions/Time-Tracking-not-work-Epic-Story-SubTask/qaq-p/2260973) teams to be tracking their time at the story level, not the subtask level.

I have been using Super Productivity since September. I find it not only helpful, but truly amazing software you have built. It is beautiful, intuitive, and useful. You, and the other 300+ contributors, should be extremely proud of yourself. Unfortunately, this creates a ceiling with respect to how well software engineering work in an enterprise can be organized. I look forward to working with you to break that ceiling. Thanks for your time.
