### ISSUE TITLE
Keyboard-Issues Web App

### ISSUE THREAD

**Issue by m4nured** [johannesjo/super-productivity#1505]
Hi,
First of all: Such great App and Project! Thank you very much!!

In the Web App on my iPhone 7 (iOS 14.7.1) the keyboard doesn’t appear, when I want to rename a task. I can mark the name but there is no keyboard to change the name or project. 
Same problem, when I want to make a subtask. No keyboard to type a name. 
Would be really great, if this could be fixed. 

Greetings, Sebastian.

**Comment by WantToLearnJapanese** [comment]
I can confirm the same problem on my Apple mobile smartphone. (iOS latest)

On the other hand, there is no problem with the iPad, which has a larger display.

I believe the issue comes from the same thing as https://github.com/johannesjo/super-productivity/issues/695 since it blocks a user from selecting the task title.

**Comment by johannesjo** [comment]
Thanks for reporting this! Unfortunately I have no iOS device available so help with this would be welcome (ideally in the form of a PR).

**Comment by reinhart1010** [comment]
I'm pretty sure this is caused by another, non-editable object placed inside the `<div contenteditable="true">`. For example:

```html
<div _ngcontent-gdp-c298="" contenteditableonclick="" class="task-title show-only-on-no-touch-only ng-tns-c298-767" contenteditable="true">Insert Semester 5 Schedule</div>
```

and this one (there's an `::after` pseudoelement there)

```html
<div _ngcontent-gdp-c298="" contenteditableonclick="" class="task-title show-only-on-no-touch-only ng-tns-c298-767" contenteditable="true">Insert Semester 5 Schedule</div>
```

In Firefox and [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox&referrer=adjust_reftag%3DcwycQ5HijdgME%26utm_source%3DProduct%2BMarketing%2B%2528Owned%2Bmedia%2529%26utm_campaign%3Dwww.mozilla.org%26utm_content%3Dmobile-page) I also can't rename the task without Select All and re-write the task name again. This behavior is similar to iOS, so you can re-test this issue without the need for an iOS device :tada:

**Comment by johannesjo** [comment]
Thanks for your input @reinhart1010 ! I try to have a look this Friday.

**Comment by johannesjo** [comment]
A fix should be out with the next version. Please let me know if it works for you!

**Comment by reinhart1010** [comment]
Tried out running from local server and it works

![image](https://user-images.githubusercontent.com/17312341/134153536-68bed536-5656-4b12-9cba-b1922d20b850.png)

![image](https://user-images.githubusercontent.com/17312341/134153544-7479cb48-f385-4ca5-92dc-ed8839218609.png)

**Comment by m4nured** [comment]
Yippeee!!! It works!!! Thank you all very much for your help!!!!
