### ISSUE TITLE
timeline wrong time zone 

### ISSUE THREAD

**Issue by pcasl** [johannesjo/super-productivity#1546]
First thank you for the awesome app! 
I didn't find a place to set the time zone for timeline. Or is there an option to change it. 

Thanks 
Li

**Comment by johannesjo** [comment]
Hey there! Normally the timeline feature should just take your local time zone. Does this not work for you?

**Comment by Brandutchmen** [comment]
Running into the same issue. My machine is in the local timezone, but my calendar is based out of a different timezone. Is there any option to support this?

**Comment by Brandutchmen** [comment]
I could also potentially look into adding this

**Comment by johannesjo** [comment]
@Brandutchmen thanks for the offer! Would you just adjust it for the timeline or globally for all time & date related stuff? I lean towards the latter, since I would assume that the timezone is wrong everywhere and not just for the timeline.

In case of the latter I'd probably put it under misc settings. The default should be the current behavior ("Auto choose time zone based on system settings").

**Comment by johannesjo** [comment]
Ah ok! Now I understand! Yes you're probably right! No need for a setting then, but to fix this within the ical parsing here:
`src/app/features/timeline/ical/get-relevant-events-from-ical.ts`
