### ISSUE TITLE
[Feature request] support RTL 

### ISSUE THREAD

**Issue by fla15** [johannesjo/super-productivity#158]
hi. I have a request for Right to Left support. 
![supportrtl](https://user-images.githubusercontent.com/30726939/55345068-446f9f80-54c4-11e9-938e-4552ff95a4d7.png)
and another request; sync with Onedrive.
very useful app. thank you.

**Comment by johannesjo** [comment]
Hey there. Thanks for the request. Never did implement RTL to be honest. What would you expect to be adjustment? I'm assuming the text alignment should be to the right. But much further than that, I'm unsure what I would need to change.

**Comment by johannesjo** [comment]
ping @fla15

**Comment by MostafaAmin07** [comment]
@johannesjo 
To support RTL languages, you need to add the attribute dir to the html tag or the body tag and set it to rtl or ltr.

Then you need to work on the design part and use property values that make it easier to support RTL,
for example, using text-align: start; is better than text-align: left; cause it will align itself in the proper direction based on the dir attribute value if not set like that a custom class will be needed to state the correct styles.

Using angular material is almost the same but,  you can't set the dir on the html tag or the body tag dynamically because angular material components won't change their direction when it changes.
However, you will need to set the dir directive on the root angular material elements and, all their child components will detect the change and apply the correct styling.
Any component that isn't an angular material or is a page on its own will need configuration to set its dir.
I would love to help you with it.

**Comment by johannesjo** [comment]
@MostafaAmin07 thank you very much for your input, that's very helpful already! Would you possibly be able to help out? I have no idea what kind of positioning makes sense logically for RTLs, so all I could do is fiddle around a little and wait for some feedback. It would make so much more sense if a native speaker would attempt to make these changes.

**Comment by MostafaAmin07** [comment]
@johannesjo I would love to.
I will make a PR and keep you up to date with the changes but, I can't make any promises with the amount of time it would take to be completed.

**Comment by johannesjo** [comment]
@MostafaAmin07 thank you very much again. I am closing this.
