### ISSUE TITLE
Ability to specify duration for tasks in pomodoros

### ISSUE THREAD

**Issue by Eikosa** [johannesjo/super-productivity#1598]
For example, if I write 5 pomodoros to a task, the duration of the task can be 25 * 5 = 125 minutes.

**Comment by TheLambdaFunction** [comment]
I would like to see something similar implemented and I think that the shortsyntax idea is totally fine.
I didn't peek the source base, but if the "AST" lexer is fairly simple in its functioning, this is something that could be achieved in _no time_ ... Then there's the next item on the whishlist..

In the Estimate UI element, a dot is displayed for every hour of estimated and spent time. Perhaps if the task is for instance tagged as a pomodoro task, instead of showing a dot every hour, it should show a dot for each pomodoro unit. No need to make the dot a tomato, if that messes too much the UI codebase 😆 

But yes, please consider implementing this
