### ISSUE TITLE
Switching to dark mode after switch to another computer

### ISSUE THREAD

**Issue by AlaricLightin** [johannesjo/super-productivity#1673]
I use SuperProductivity on two computers: desktop with Windows 10 (21H1 version) and laptop with Ubuntu Linux. Database is syncing by Dropbox. I prefer light mode. But when I switch from one device to another SuperProductivity settings switches to dark mode.

Version used: 7.7.0 on both computers (from Microsoft Store on Windows and snap on Linux).

**Comment by johannesjo** [comment]
Thanks for your question. Do you have global dark mode activated on either one of the two systems?

**Comment by AlaricLightin** [comment]
No.

**Comment by johannesjo** [comment]
And this happens even if you switch from dark mode to light mode on the other system? 

How it should currently work is that the dark mode setting isn't synced (since you might have a different preference for each device) and as dark mode is the default setting this might be why there the dark mode is activated.

**Comment by AlaricLightin** [comment]
1. Usually I work on desktop. With light mode.
2. In some moment I need laptop. I turn on it and run SuperProductivity. After that I see dark mode (although last time it was light mode).
3. I switch to light mode and do some work. After that I close app (and see message about uploading file).
4. I run SuperProductivity on desktop and see dark mode. Although it was light last time.

**Comment by johannesjo** [comment]
Thanks for the explanation. So far I am unable to reproduce this, but I'll have another look.

**Comment by stefabat** [comment]
I have the same issue. I work on 3 different computers, sync between them via Gdrive (by the way, I tried to open the .json file and it is not human-readable, is that supposed to be that way?).
Since the last update (7.7.0) I have this issue, when I switch computer it starts the app in dark mode. If I then close the app and reopen it, it sticks to the light mode. So this issue only appears when the settings file gets synced from another computer. Maybe it plays a role the fact that I use the flag `--force-dark-tray` to get the white icon in the tray?

**Comment by johannesjo** [comment]
> by the way, I tried to open the .json file and it is not human-readable, is that supposed to be that way?

If you did enable compression, then the answer is yes. 

I'll try to have a look at this tomorrow (unless someone else is volunteering for this :)).

**Comment by johannesjo** [comment]
I checked again and I am unable to reproduce this. Is the setting persisted if you deactivate syncing, close the app and start it again?

**Comment by stefabat** [comment]
Hi, by disabling the compression I can see inside the .json file, thanks.

Now, to the issue, here is the log from the startup from terminal
```
10:32:43 ⟩ superproductivity --trace-warnings
10:32:45.550 › { enabled: null, showDevTools: false, mode: 'bottom' }
Saving backups to /home/stefano/.config/superProductivity/backups
10:32:45.648 › Saving backups to /home/stefano/.config/superProductivity/backups
(node:8145) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `superproductivity --trace-warnings ...` to show where the warning was created)
[8179:1124/103245.704927:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
10:32:46.091 › No custom styles detected at /home/stefano/.config/superProductivity/styles.css
```
I tried your suggestion and yes, the setting persists without syncing if I close and reopen the app. But the same is true even with syncing on, as long as I do it on the same machine. Anyway, here is a step-by-step list to reproduce the issue:

Steps to reproduce:
1. Disable syncing and dark theme on both machines
2. Make sure that on both machines, if I close and reopen the app, these settings persist
3. Open the app on machine 1, enable syncing (the .json file gets uploaded), and close the app
4. Open the app on machine 2, everything looks good, because syncing is still disabled
5. Enable syncing on machine 2, when prompted about which data to use, select remote data
6. As soon as the data is downloaded, the theme switches to dark

Additional steps in the other directions:
7. Disable dark theme on machine 2, make the app upload the .json file
8. Close the app on machine 2
9. Open the app on machine 1 
10. The app automatically downloads the data from Gdrive, as soon as it is downloaded it switches to dark theme

Also, I messed up with the updates, and used two different versions of superproductivity on two machines, and now every time it downloads the data, I get the message "Legacy data detected while importing, do you want to try to migrate it?" and even though I always say yes, this message now pops up every time.

**Comment by johannesjo** [comment]
Thanks for further digging into this! Is there by any chance an older version installed on the other machine?

**Comment by stefabat** [comment]
There was at one moment. I updated to 7.8.0 on one machine, then open 7.7.0 on the other one, and that message popped up. I don't remember if I then just closed the app, updated it and then reopened it, or if I used it anyway at 7.7.0 for a while and updated it later. Anyway, after it came up the first time because of the version mismatch, it never went away, even though now I am on 7.8.0 on all machines.

**Comment by johannesjo** [comment]
I was finally able to reproduce this. I am working on a fix.

**Comment by johannesjo** [comment]
I think I was able to fix this. Thanks again @stefabat for all your help! 

The fix should be out with the next release. Could you check again then please?

**Comment by stefabat** [comment]
Sure, no problem. Thank you for quickly fixing this!

Cheers
