### ISSUE TITLE
Labeling and icons

### ISSUE THREAD

**Issue by makkasi** [johannesjo/super-productivity#1685]
First to say that this is the only app, that can do everything I want during my work day and daily to do tasks. But there are some basic features which for me are one of the most used features and still they have not logical look and feel. 

## Problem Statement
I think that dialog icon for task is really confusing. I searched about an hour how to create repeated task. After that hour I came here and read few times that there is some advanced option on right click. I could not find it. Finally it seems that there is not advanced option at all. 
Seems that I have to click on the dialog icon, to open options menu. First the dialog icon doesn't connects with what it really does - opening options. Second the Tooltip over this icon is "show additional info" and this is not info. Info is something that you can read, you can inform yourself and you can close it. How could I know that the info is actually the most important menu of the app - i.e. setting the task that I created. 

## :grey_question: Possible Solution
This is rather task options or task settings. So I think that there should be an other icon with gear and an other Tooltip. 

## Problem Statement
Also may be I am the broken one, but the task creation is strange for me. When I click on the plus to create task, then it appears input field and before the input field there is icon. How should I  know that this icon is active button? It doesn't look like a button, it is at the beginning of the row, and it is not beside an other icon that could be button. I clicked it just by accident. 

## :grey_question: Possible Solution
Solution is to move this icon at the end of the row, next to the other icon. The second icon which is for adding the task to top of the list is OK, because it is not at the beginning, but it is at the end. Also I don't see problem these icons to be put next to each other. And if possible it is good if they have tooltip on hover - currently they don't have. 

## Problem Statement
Again, may be it's only me, but adding task to backlog.... No menu, no Label, nothing that is written backlog. I go through all projects. I search in the projects settings. I click today.. Nothing. Finally I spotted half cut icon at the bottom of the page. OK. I clicked at seems that this is the backlog.  But when the icon is cut that way is hard to find. The icon looks like handle and  not as actual button. 

## :grey_question: Possible Solution
Changing the icon at the bottom to be visible. Adding tooltip to that icon if possible. May be changing the icon with more speaking icon for backlog, like may be calendar and question mark. Or case handle. Also may be putting header Backlog on top of the backlog list.

**Comment by johannesjo** [comment]
Hey there! Than you very much for opening this up! You make some very valid points! You seem to have a good feel for these kind of problems. What icon and what text would you use for the "additional info panel" ?

A list of the available ones can be found here:
https://fonts.google.com/icons?selected=Material+Icons:book

**Comment by makkasi** [comment]
Hi, 
I would use just the icon:
settings


An some joke like, but could work. Option is to use: 
local_florist
This one looks little bit like gear icon, also it has goal. 
"How can I best achieve it now" - water the flower
"what do I want" - Tulip, rose
"Why do I want it" - For gift
Add attachment- the flower speaks little bit about image upload.
And the leaves a little bit like a clock arrows. :)
Certainly if person looks for the gear icon will manage to see the flower and if he doesn't know what it is, it will click on it, and every person that uses the app should click at least once to work properly with the app. 
Regards.

**Comment by johannesjo** [comment]
@papernoise may I ask for your input on this? :)

**Comment by makkasi** [comment]
Then you could use two icons for these, one over the other. In this case setting icon, over the current icon. This way the dialog icon will be field, and the setting icon will speak for itself. 

Also there is option to use just the settings icon in its two matterial icon stages: filled and outlined.

**Comment by papernoise** [comment]
@johannesjo Sorry for the delay, had a very busy week. But, I'll gladly add my 2c here!

## Ddialogue icon
I think we all got so used to this icon that we don't pay much attention to it anymore. Over time I think more features have been added to the panel, so now the icon ideed does not fully reflect what the panel does.
Maybe it's a good idea to recap what the panel will enable you to do when opened:
- Tweak the time tracking and estimate
- schedule a task
- add notes (description)
- add attachments
- and set the task to repeat

Now, these are not just settings, it goes a bit beyond that. The type of actions that are performed via the panel are pretty diverse. What they have in common is that they all live on a panel that moves in or out of the window. 
Some icons that I think would work:

**TOC**: it kind of reflects the nature of the sidebar, though it would work better if the dots were on the left
**Vertical split/ View sidebar**: These work well in my opinion because they focus more on the fact that it's a sidebar that shows up, not so much on what it does. Which leaves it open (in case more stuff is being added in the future)
**chevron left/right**:  another neutral solution, a little arrow pointing left or right depending on the state of the panel (open/closed), though I think the previous one would probably be more obvious.

## new task dialogue

> Solution is to move this icon at the end of the row, next to the other icon.

That seems like a good idea to me. Btw. can we add a shortcut to toggle between top/bottom?

## Backlog

@johannesjo I think we had been discussion some changes in the past hadn't we? 
I think there wasn an idea of making the backlog panel be a little open so it's more discoverable, so it's kind of like this by default:
![Screenshot 2021-12-11 at 17 55 31](https://user-images.githubusercontent.com/1595523/145684955-4ea612c5-4f73-4657-908a-196c159a2a22.png)
But I need to look up my notes...

**Comment by johannesjo** [comment]
Thank you very much @papernoise once more! I decided to go with the vertical_split icon as the chevron didn't look right and the toc might have some other meaning (though I am not sure what :D)

I created a new issue for the backlog adjustments since this might require a bit more re-design, as the backlog possibly should be over the content and not the other way round.

**Comment by johannesjo** [comment]
Please let me know if you have any more thoughts about this! Especially once you see it "in action".

**Comment by johannesjo** [comment]
If I am not mistaken, this can be closed now right?
