### ISSUE TITLE
the 'tasks' category shortcuts are not working

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#1778]
Also, not sure if related; the 'tasks' category shortcuts are not exactly working. I am a new user and do not know if this is normal behavior or is related to this bug.

I pressed 'w' to go to work view, then pressed 'tab' to focus on the first task in list. 

Firstly, it is almost impossible to notice the tasks are tab-focused, the only indication was the slightly rounded corners. 

Anyway, once a task is tab-focused, 
- 'j' does not go to the next task, 'k' does not go to the previous task.
- 'q' opens the task context menu but once dismissed, the task is unfocused. Pressing tab here will cycle the sidenav, there seems to be no obvious way to refocus to the task list. 
- 'i' shows the info sidebar, but pressing i again does not hide it.  The task is unfocused again. clicking on the task to hide it interestingly focuses on the first task in list again.
- 'edit title' and 'add subtask' shortcuts are probably affected by this bug.
- the other shortcuts mostly work like 'd', 's', but the UX problem of focusing to a task persists.

_Originally posted by @rreo in https://github.com/johannesjo/super-productivity/issues/704#issuecomment-1001190580_

**Comment by johannesjo** [comment]
@rreo I created a new issue for this. Thank you!

**Comment by johannesjo** [comment]
@rreo are you by any chance using a touchscreen device such as the microsoft surface?

**Comment by rreo** [comment]
Yes

Device: Microsoft Surface pro-1796.
Version used: Desktop app version 7.8.1 / Web app version 7.8.1
Operating System and version: Windows 10 Pro 21H2
Browser version: Microsoft Edge Version 96.0.1054.57 (Official build) (64-bit)

My surface pro is docked and I connected an external monitor to it.

Copied from https://github.com/johannesjo/super-productivity/issues/704#issuecomment-1001161895

**Comment by johannesjo** [comment]
That might explain the problem. Thanks! I'll try to work on it.

**Comment by johannesjo** [comment]
This seems to be caused by a chromium bug. Please star/upvote!
https://bugs.chromium.org/p/chromium/issues/detail?id=1088262
https://bugs.chromium.org/p/chromium/issues/detail?id=102811
https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/results/

**Comment by rreo** [comment]
It is fixed!

**Comment by rreo** [comment]
This issue is fixed. Thanks a lot. 

I love this app and have been using it for some time. Here are some other UX issues I've noticed using the keyboard shortcuts if you're interested. 

### 1. Show and Focus/Hide the sidebar 

Pressing 'Shift D' focuses on the sidebar (specifically the Today button', pressing 'Shift D' again does nothing. Then 'escape' hides the sidebar, along with the icon to show it. 'Shift D' does not show the sidebar again. The show navbar icon is gone. I have to resize the window for it to reappear.

Expected flow: 

- Shift D to show sidebar and focus on the last-focused item. Shift D again to hide.

### 2. Navigating to a project, then it's task list:

Tried 'Shift F' but only searches for tasks. I could search for a task in that particular project, which jumps to the project's task list but I'd prefer to search for the project name to bring me to the project list.

Tried another method: 'Shift D' focuses on the sidebar, navigate with down arrow keys to the project name, and 'enter'. It brought me to the project's task list page but I have no way to focus on the task list except tab cycling each element to reach there. 

Expected flow: 
- Focus on sidebar, down arrow keys to navigate to project, 'enter' to select project, project page shows, task list automatically focused or focus first item of task list (have to implement this shortcut, or make the 'j' shortcut (select next task) do this). 
- (Preferable) Or search project name, select project, task list automatically focused or focus first item of task list. 
 
### 3. Adding new tasks
 
i. After 'shift a' to add task then 'escape' to cancel, the task list is out of focus. I have to tab cycle elements to reach there. 

ii. When 'shift a' to add task, there is no key to toggle the two buttons provided there; 'add task to top of backlog/list', 'add task to top/bottom of list.'. I'd have to reach for the mouse and click them.

iii. Is there a way to make it add to bottom of list by default, or remember my last settings? I think this would be helpful and convenient. 

Expected flow:
- Task list automatically focused after 'escape' add new task.
- Shift-A to add new task, 'tab/shift tab' to focus on toggles, 'enter' to toggle.
- Remember my last settings for adding new task.
- Implement a shortcut which focuses on the first item of task list. (possibly with the 'j' shortcut key (select next task) with extra logic)
