### ISSUE TITLE
Cant sync web.de webdav

### ISSUE THREAD

**Issue by BenHerbst** [johannesjo/super-productivity#1797]
- Version used: Freedroid
- Operating System and version: Android and Pc
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

Webdav sync works.

### Current Behavior

![IMG_20220104_144303.jpg](https://user-images.githubusercontent.com/83538916/148068231-d68e6626-9ffa-475d-ab91-50f146a20600.jpg)
I log in but i get gate way 504 error.

### Steps to Reproduce (for bugs)

1. Try to connect webdav
2. See error

**Comment by BenHerbst** [comment]
![image](https://user-images.githubusercontent.com/83538916/148079711-e1979aad-1a79-4e0f-a93b-3737be544602.png)

**Comment by johannesjo** [comment]
Thank you very much for reporting this. A  504 indicates some sort of server configuration issue at first glance. In case there is something to be done on super productivitys side of things, PRs are welcome, but as I don't have your particular setup available, I won't be able to fix this myself.

**Comment by BenHerbst** [comment]
Okay, then I think I will use drop box or create a PR if I find a solution.

**Comment by SDhuangao** [comment]
> Okay, then I think I will use drop box or create a PR if I find a solution.

Same network problem here, my super-productivity windows version can connect to my raspberrypi nextcloud perfectly (although I need to create the json file manually). But on my android phone, I constantly encounter **Unkonw Sync Error: Error: Network Error**, I am not sure where the problem is. I though it was the hosts problem, then I change the hosts file to direct the ip address (I only use lan to sync, so the ip address is 192.168.xx.xx) to the hostname (raspberrypi), this didn't work. Did you solve the problem yet?
