### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by MarianyFerreira** [johannesjo/super-productivity#183]
What are the changes to come up with an android app on Play Store?

**Comment by MarianyFerreira** [comment]
You can now add the app to your phone's home.

For this you need to install the Super Productivity extension in App Chrome Mobile. After this will appear a message asking if the user wants to include the App on the home screen.

**Comment by MarianyFerreira** [comment]
App notifications do not work. In case of smart band and watches connection is realy important the notification push

**Comment by johannesjo** [comment]
Hello @MarianyFerreira an android app is on the to do list, but not really on top of it. Much of how the app works is tailored to using it on the desktop and for some of the concepts I'm not sure how well they will translate to mobile. Just to name one example I wouldn't know if idle time tracking makes sense in any way for mobile. 

Personally I use the web app on mobile just to add a task, when I think about a new feature or something and sometimes for the reminders. Apart from that I haven't - on a conceptual level - really figured out, how the app could work on the platform. Should it be more a general purpose to do list manager like microsoft todo, should it do exactly the same as the desktop app (maybe with some extra stuff to make it work better) or should it be just an extension of the desktop application. To be honest, I don't really have good answers to those questions, but would be curious to hear your thoughts on this matter.

**Comment by MarianyFerreira** [comment]
I believe that the desktop application fulfills what is proposed by it. In my opinion, if it were to make some adaptation to the Mobile, small things, without changing the functionalities (they are very consistent). It would only change things like notifications, maybe it would create a widget to keep track of the timer of a task, stop, etc.

The app design fits well on small screens so I do not think it would be a major concern, unless distribution stores (Google Play and Apple Store) require a design pattern

**Comment by KonTy** [comment]
@MarianyFerreira this is so philosophical but this app is designed for the desktop at the core, Most of productive things you do are on the desktop, and even though it would be nice to have it on a phone there are so many things we want to do on the desktop that I wouldn't want to spend time doing it for the phone. It just doesn't make sense currently. 

Believe it or not even though Chromium and Electron and Android are all Google products it is not easy to make electron apps run on Android.

**Comment by johannesjo** [comment]
@KonTy Just putting the app into a cordova wrapper would not be too hard actually. Publishing to the store is a little bit annoying though.

@MarianyFerreira In general I'm more worried on the conceptual area, because I don't what the typical use case would look like. I might be wrong, but I am assuming that 99.9% of the people using the app have an office job, in which they work from a desktop computer or laptop. Having a smartphone laying on the table nearby and using that, doesn't make too much sense to me.

I can however definitely think of some interesting integrations with a smart watch like you described. I don't own one, but I definitely see the appeal of a combination. But doing so would require quite a bit of work, while the target audience might be a bit small. I'm totally open for everything (Pull Requests and more detailed suggestions), but at the current point of time, I think that it makes more sense to dedicate my own time to other features and bug fixes.

**Comment by jiongxuan** [comment]
@johannesjo @marianyfs @KonTy  I’ve resolved the issue. Please refer to this PR for details: 

- https://github.com/johannesjo/super-productivity-android/pull/57
- https://github.com/johannesjo/super-productivity/issues/3527

Considering that many are interested, here’s a brief overview of the changes:

I have taken steps to address the longstanding issues related to offline support and CORS in the Android application. These updates are designed to enhance the user experience by enabling offline functionality, resolving security-related CORS issues, and ensuring a smooth transition for existing users. I welcome any questions or feedback from the community to help refine and improve the solution further.
