### ISSUE TITLE
Repeating Tasks

### ISSUE THREAD

**Issue by daya** [johannesjo/super-productivity#187]
To analyze my time spent in everyday tasks leading to efficient time allocation a very helpful feature is a "Repeating/Reccurring Tasks" e.g. everyday chores/tasks in our home that need to be done.

Currently I have to create the same task over and over again to capture my time spent, hoping that when a Time Spent report is available I will have a good insight into what consumes my time.

**Comment by johannesjo** [comment]
Thanks for the suggestion! Agreed! It would be good to have this feature.

**Comment by johannesjo** [comment]
I was sitting in the train today and were able to write up a rough concept on how to implement the feature:

* We call the model repeatTaskCfg, because I always write reoccurring wrong (:
* On a model basis we use separate task every time, because otherwise we get in trouble with deleting, sub tasks etc
* Use separate model and feature for repeatTaskCfg because it is probably cleaner
* A visual clue is needed to indicate a repeating task in list
* Add a new stat for reoccurring tasks on the metrics page
* Add button to context menu for making a task repeat
* Jira/Git Issues can't ever be repeating because it doesn't make sense
* Sub Tasks can't be reoccurring beceause it doesn't make sense
* Reoccurring tasks can't be moved to the backlog because it doesn't make sense => if possible we will indicate this via a not allowed icon, if not we just don't do it (check dragula for this maybe)

### Creating the tasks once configured
* Reoccurring tasks will be created as needed (when a task with the creation date of today is nowhere to be found) after loading a project
* A Snack should appear to inform the user about that and to not confuse them with yesterdays entities if present, because the user forgot to mark them as done

### Model Outline
We keep the model simple for now. Later we might add more complex patterns to when a task should reoccur.
```ts
export type RepeatOpt = 'EVERY_DAY' | 'possiblyMoreLater';

export interface RepeatTaskCfg {
  id: string;
  repeat: RepeatOpt;
}

export interface Task {
  // ...
  repeatTaskCfgId?: string;
}
```

### Task Side Effects to consider
* Deleting Task => needs to consider if there is any archived task with the same repeatId and if not delete the reoccurring config OR ask the user if all should be removed OR mark as done??? 
* Archiving Task => nothing
* Add Sub Tasks => nothing
* Finish day => Reoccurring tasks, should always be marked as done
* Remove Reccorruing Config/ Deactivate => Even if there are any tasks left with the config id remove the model entry.  Leave repeatId on task to identify tasks belonging together, in case we want to use it for stats or something.

**Comment by KonTy** [comment]
First of all this is an awesome spec!!!

I have a couple of questions.

> export type RepeatOpt = 'EVERY_DAY' | 'possiblyMoreLater';

I know this is a first attempt. Here is an idea to consider 

Daily
Weekly
Monthly 
Yearly
or
Reoccurs every X weeks on checkboxes for each day of the week. 

In my experience this can handle pretty much every case. Here is an example 
https://www.uvic.ca/systems/assets/images/screenshots/emailcalendar/facultystaff/outlook2010/recurringmeeting2.png

 
> Deleting Task => needs to consider if there is any archived task with the same repeatId and if not delete the reoccurring config OR ask the user if all should be removed OR mark as done???

Good call!


Other things to consider 
How to do reminders of recurring tasks
How to handle due dates for recurring tasks.

**Comment by johannesjo** [comment]
The feature is implemented and should be available as pre release as well as in the snap edge channel soon. Please let me know what you think!

**Comment by rubensfredrick** [comment]
Hi there,
I was trying to find the recurring option on a task. Couldn't find it. You say it's already implemented ? I need to set a task so it reoccurs bi weekly

I am using the app in linux : Super Productivity 2.13.3

**Comment by KonTy** [comment]
> Hi there @johannesjo,
> I was trying to find the recurring option on a task. Couldn't find it. You say it's already implemented ? I need to set a task so it reoccurs bi weekly

Have you looked under "...\Advanced" in the menu?

![Reoccuring](https://user-images.githubusercontent.com/9524513/67586656-fee81d80-f706-11e9-9c69-aecdbf982846.JPG)

**Comment by johannesjo** [comment]
@rubensfredrick unfortunately currently super productivity only supports repeating tasks on a weekly basis.

**Comment by nicola-lunghi** [comment]
Hi is this still enabled? would be nice to have
!!!

**Comment by johannesjo** [comment]
@nicola-lunghi yes this still exists.

**Comment by facorread** [comment]
Hi @johannesjo , thanks for your work on super-productivity. I'd like to suggest reopening this issue to see if anyone would be interested in contributing options for monthly- and yearly-repeating tasks. Thank you.

**Comment by johannesjo** [comment]
As a quick update: I am currently working on a calendar integration. It probably makes sense to wait until I am done with that (which might take a while).

**Comment by aliyazdi75** [comment]
Hi @johannesjo, thank you so much for this wonderful tool.

I wanna suggest some concepts that could make sense to be considered in the repeated tasks that exist in Microsoft to-do too.
1. They should be scheduled with reminders and added to the scheduled list.
2. The repeated tasks should contain their first estimate time, tags, description,... until we change them.
3. A section should be there in today list to add the scheduled tasks easily.
4. The last suggestion that you mentioned in the last comment.

**Comment by johannesjo** [comment]
@aliyazdi75 thanks for the additional suggestions. Makes all a lot of sense!

**Comment by AA595** [comment]
Hi @johannesjo.
 I use super productivity version 6.40 on Ubuntu 20.04. I installed it using the snap package manager. The repeat task option simply doesn't exist here! When I right click on a task, It doesn't even have an advanced option. Is this a bug or has the feature been removed? Or have you not added this feature for Linux versions yet?

**Comment by johannesjo** [comment]
The task repeat config can be found in the task side panel which you can open by clicking on the little speech bubble when hovering a task or the right key when a task is focused with the keyboard.

There are some limitations. You can''t repeat tasks that:
1. are created from an issue, because it makes no sense
2. are sub tasks
3. have a reminder set up (though I want to change this one in the future).

**Comment by lonyelon** [comment]
Just ended up here since I had set up a daily task with subtasks, and it repeats the main task and not the subtasks. This would be a cool feature to have.

If I have time next week I'll check the code and try to add this functionality. Program is great btw, you did an excellent job!

**Comment by johannesjo** [comment]
@lonyelon this is great news! Let me know if I can assist you in any way!

**Comment by lonyelon** [comment]
@johannesjo tell me if this makes sense to you as the main dev of the project:
* A repeating task should keep its original length (time to complete).
* A repeating task should keep its original subtasks.
* Its subtasks should also keep their original length of time.
I don't know if this makes sense to you or not, but if it looks good to you I'll open an issue (if there aren't any about this already) and start reading the code to at least know what to change in the future.
And thanks a lot again for the software!

**Comment by johannesjo** [comment]
> * A repeating task should keep its original subtasks.

Imho this should be optional, but maybe the default?

> * Its subtasks should also keep their original length of time.

This is a bit tricky, but in general I would suppose so?

We probably should also make a setting for this. Just a simple checkbox labeled "Recreate sub tasks". I am also not sure if we just should re-create the task's "last" instance's sub tasks or if we should provide some dedicated config fields for this as well. The later feels a bit cleaner, but also a bit convoluted. Not really sure. What do you think?

**Comment by lonyelon** [comment]
> Imho this should be optional, but maybe the default?

I (as a user) thought it worked that way by default, so maybe it makes more sense for it to be the default. That said, many people use this software and idk what their opinion is. If I find some time to add it I'll make it as an optional feature.

> This is a bit tricky, but in general I would suppose so?

Yeah, I don't see why not.

> The later feels a bit cleaner, but also a bit convoluted. Not really sure. What do you think?

Yes, seems like some over complication, the first option makes more sense to me.

As I said, I'll start working a bit if I find some time and add this.

**Comment by nunojsa** [comment]
> have a reminder set up (though I want to change this one in the future).

In my opinion I think it would be useful to actually have a setting where we could also setup a repeating remainder notification for this periodic task. Would this make sense for you guys?

Other thing that comes to my mind is another setting to automatically add this task to the today list (obviously on the proper day)...

**Comment by johannesjo** [comment]
Sorry, for taking my sweet time to post an update. I think the basic goal should be to achieve a functionality like google calendar or Thunderbird offer for reoccurring events. 

It should be possible to:
1. Select several week days similar to how it is now.
2. To create monthly tasks.
3. To either have an "all-day task" (just shows up on the list) or to specify a specific time (shows up with a reminder).

Imho less important, but maybe also nice to have would be
1. Biweekly or triweekly (is this a word?? :D)  tasks
2. Yearly tasks
3. Re-creating sub tasks  (as optional feature)
4. Even more funky re-creation patterns

Still unclear to me is (lacking a good concept):
1. How to deal with the task creation or in other words when exactly should a task show up in its list and how to deal with all it's future instances?
2. Should task meta data such as the description be the same among all instances per default? 
3. In what way to create sub tasks. Probably a simple solution is best, that just uses the title (maybe with the short syntax included) but ignores everything else. I'd like to keep things as simple as possible for this.

As I said in another place (sorry forgot where) it probably makes sense to wait for the changes coming with the calendar feature, which is still in a very early stage. I am thinking about merging the feature back to master in it's unpolished and a little bit buggy state in order not to block further development on this, but am still undecided. The most critical blocker for it is this: https://github.com/fullcalendar/fullcalendar-angular/issues/358 in case someone wants to help :)

**Comment by johannesjo** [comment]
Thinking about it, I think that it is best to restart the discussion on this in a new issue. I think much of what is posted here, is not relevant any more.

Please follow the discussion here (and upvote the issue if you like to see the feature):
https://github.com/johannesjo/super-productivity/issues/948
