### ISSUE TITLE
Recurrent task cannot be deleted

### ISSUE THREAD

**Issue by nkrot** [johannesjo/super-productivity#1890]
I experimented for a few days with recurrent tasks and can see that they can not be deleted directly.
The method of deletion that worked is: make the task non-repeated, delete the task. In my opinion, this is a workaround rather than a correct method. Deleting a repeated task should be as simple and straightforward as deleting any normal task.

### Your Environment

-  Version used: 7.9.1 (deb)
-  Operating System and version: Ubuntu 18.04
-  Desktop Environment: MATE
-  Browser Name and version: Firefox 89.0

### Expected Behavior

Once a recurrent task was deleted, it must not appear on subsequent days. Deleting a task means exactly deleting a task forever and not just deleting for today (which is closer to unscheduling).

### Current Behavior

A recurrent task (scheduled to every day) appears on a new day upon start of application even if the task was deleted on the day before.

### Steps to Reproduce (for bugs)

1. create a task
2. make it repeated task, select all days
3. delete the task, it will disappear from project
4. come back next day, see the task is here

**Comment by johannesjo** [comment]
Thanks for opening this up. You need to remove the repeat task config (in the task side panel click on "Repeat" and then on "Remove" in the Dialog that opens) if you want to remove a repeating task completely.

**Comment by nkrot** [comment]
@johannesjo , thank you repeating what I said in the intro.

**Comment by johannesjo** [comment]
Sorry @nkrot,  I am dealing with a lot of requests for this project every day (which I do in my free time for free), so please forgive me.

I disagree that repeating tasks should be as easy as as deleting a single task, since there might be a lot of tracking data stored on it, which one could delete accidentally (maybe it's just a different perspective from using the app a lot longer than you have). A confirm might be an option, but this could also be annoying in case you just want to delete this particular instance of a repeating tasks, which for me happens often for a daily repeatable tasks.

**Comment by nkrot** [comment]
hi @johannesjo 
would it make sense to word the act of deletion more specifically (in the context menu that appears upon right click), something like `Delete current instance of recurrent task` instead of generic `Delete Task`? At least this wording gives information about what is gonna happen and will stop ppl from writing similar tickets that you will close w/o reading, still wasting your time.

**Comment by johannesjo** [comment]
That's a very good idea! I'll implement it!
