### ISSUE TITLE
Meeting timer to track time, but suppress notifications for a period of time.

### ISSUE THREAD

**Issue by StewPedassle** [johannesjo/super-productivity#1904]
## Problem Statement
Super Productivity can introduce distractions with notifications that are unnecessary during longer events where one wants to still track time (e.g., meetings and presentations).  The distractions include (1) pom end / break start, (2) not tracking time for x mins, and (3) being idle for x minutes.

## :grey_question: Possible Solution
Either a do not disturb button or an extended task timer that will (1) allow tracking of time to tasks and "working today" timer, (2) bypass pomodoro settings, and (3) stop noises and OS-level notifications for a provided duration.

An example implementation would be:
 - Provide button or timer adjacent the current pomodoro timer.
 - When actuated, prompt the user to set and confirm the duration or end an extended session. 
 - Once confirmed, hitting the button again would allow the user to end or extend the session via the same prompt.
 - At the end of the session, SuperProductivity provides an OS-level notification and an in-app prompt that lets the user dismiss the notification, start a pom, start a break, or extend the duration by another alterable time period.

## :arrow_heading_up: Describe alternatives you've considered

A potential quick and dirty alternative could be an "extended pom" button. i.e., actuating the extended pom button changes only the current pomodoro session to a default time (e.g., 1 hr). This would eliminate one of the distractions and allow for continued tracking of time. But, it would not eliminate the without break notification, idle notification, or scheduled task pop-ups.

## :heavy_plus_sign: Additional context

Associated settings or features, ordered by my opinion of importance, include:

1. a default DND duration
2. accept common time formats like "1:30" for "1h 30m". This is applicable to the program overall, but would need different parsers for time or duration.  That is "1:30" is "1:30 am" as a time, but "1h 30m" as a duration. 
3. default extension time

Related:  My suggestion is kind of similar to at least one previously opened issue  (e.g., #1621), but I opened this to provide a more concrete idea for a feature.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for opening this up! 

This is a tricky one! From this use case's perspective a do not disturb toggle button makes probably most sense (and I totally agree that what you describe is a bit of a problem). On the other hand I don't want to clutter the UI for new users (and people not needing this) since it might not be obvious what this is about. It also would add complexity on how to deal with different scenarios of coming back from the  DND mode (probably best to just restart all timers, but maybe I am overlooking something).

In an ideal world I would like it to be the other way round. If you're using teams in a browser for example, the rest of the browser tabs are put in a DND mode which blocks all notifications for that time. Maybe this could be an angle to tackle this?

**Comment by EngelPika32** [comment]
Hey there! I've actually looked into such a thing as well. But not the same way as requested here.

> 1) pom end / break start

I don't use pom [pomodoro, I assume] (I have 'take a break' reminders ;)) – There probably should be an easy way (optional toggle) for pom, to "stay in current session". This can be used if a task/meeting is to be expected to extend the current session time, as well as if a break is expected to be longer. The timer would just continue counting without changing the state (working/break), and hence without taking focus.

> (2) not tracking time for x mins

Just don't work on a task and then 'dismiss' the time-tracking reminder?
The time-tracking reminder doesn't take focus. Hence I don't see it disturbing anything?? 

> (3) being idle for x minutes.

That one actually annoyed me so much, I disabled it.
Like, sure, change the view. But I see absolutely no reason to take focus. 
This is where an option in the settings could be added to enable/disable the "take focus". 

- - - - -
I'll extend with the unlisted notifications:
(4) work time extends expected time

This is where I'd start saying "this is tricky". 
Personally, I'd see a "Simple Button" (similar to a simple counter, except it just toggles smth.) as an option of implementing it in the UI. Having the color and possible icon change to indicate it being active/not-active.
This allows to:
- Make it opt-in
- Reduce clutter for new users
- Can be extended for possible other toggles/triggers _(It essentially triggers instead of being triggered)_

At least for (4), this button could simply change a feature flag, which then prevents notifications from being sent to the OS (we could still log them in the console though).
And if it's implemented via feature flags, then we should probably add a section in the options to view & edit them manually (just in case). Would allow switching a feature permanently without having the button enabled as well. 
_(And I know, that this is essentially what all the 'option'-checkboxes do. The difference lays between: "changed once during setup", "changed during use")_


- - - - - 
> In an ideal world I would like it to be the other way round. If you're using teams in a browser, for example, the rest of the browser tabs are put in a DND mode which blocks all notifications for that time. Maybe this could be an angle to tackle this?

Uh, for one, isn't that contra-productive?, and for two, this already exists (?). 
1. It only accounts for browser usage - the ideal world should at least have smth. like this implemented on OS level, or?
2. Each and every site could potentially miss-use this. And you'd have to account for situations in which you want to have notifications from more than one tab.
3. At least my notifier would allow me to enable DND mode (on OS level), preventing all notifications from showing up (and optionally logging them for later). *(though, doesn't handle window-focus and hence focus-grabber; It's a notification manager and not a window manager after all)*.
I'm pretty sure, I saw such an option in the browser as well. Though I don't need this, the way I handle noisy (web-)apps. Hence, I dunno anymore.

I mean, it obviously depends on the software you're using. But there are options out in the world. 

I agree that noise should be handled where it emits. If a notification manager is used, then that manager is creating the noise (sound/pop-up) and then that manager should implement DND. 
However, if the own app creates the noise (like we have it here with pom; in-app pop-up, etc.), then the own app should handle the noise.

**Comment by devinaconley** [comment]
Hey folks - I often hit the same issue during meetings where the idle handler triggers, takes focus, and switches my desktop to another workspace

Just throwing in a +1 for this suggestion from @EngelPika32
> This is where an option in the settings could be added to enable/disable the "take focus".

I think something simple like this would cover a lot of cases. I personally don't mind correcting the idle vs task after the fact

---
As an aside, @johannesjo this is an awesome application, thanks for all your work!
