### ISSUE TITLE
Using dropbox I get all the time "Conflicting data"

### ISSUE THREAD

**Issue by sylock** [johannesjo/super-productivity#2012]
### Your Environment

* Use the web client 7.11.2 on Firefox 98.0.1 64 bits on PopOS! 21.10
* Use the Android version from the marketplace version 7.11.2
* sync enabled on both clients onto dropbox

### Expected Behavior

The sync is done smoothly with atomic updates depending on the client I'm using.

### Current Behavior

Using 2 clients frequently to make updates results in conflicting data. Then I must choose if I keep the remote or the local data with potentially a lost of data.

### Steps to Reproduce (for bugs)

1. configure both clients as described
2. add a task from one client and **do not** sync
3. sync on the other client (without modifying anything)
4. sync the first client
5. you get a sync error

### Error message from the UI

```
Sync: Conflicting Data
Update from remote. Both local and remote data seem to be modified.
```
Then I must choose if I keep the local or the remote data.

**Comment by ErezAmihud** [comment]
It sounds like the syncing does not take into account the data that was changed, only when it was changed.

We should make a record of what you changed from the last sync you did (from that device) and sync obly that

Adding a machenism to check what was changed and then only if the specific field was changed it should show this error.

NOTE that it might be best to use a proper db platform to do the syncing and leave behind the json files.
Mongodb offer free cloud plan for small databases, it is json oriented so interface is the same, and I think it support notifications on change. or use realtime db of firebase google, mayve even better because it is meant for syncing and is more json orianted then mongo.

I did not look at the code, this is only an assumption, I am not sure if I will have time to check it but it might help someone.

**Comment by thelastindian** [comment]
This issue still persists
It is very unreliable

**Comment by KronosTheLate** [comment]
Every time I make a change in the mobile app, and thereafter open the desktop app, I get a warning like the following:
![image](https://github.com/johannesjo/super-productivity/assets/61620837/46c333bd-8b3b-4df1-82e5-6dc3fde09378)

The problem is that the time and date for the "Last change" on "Local" is the current time and date, but I just opened the app, and have not used it today. So it seems as the desktop app thinks it has made a change the moment I open it, before it pulls in from remote. I see two possible resolutions:

1) Try to merge the changes. As there are no actual changes from the desktop-app, there should be no conflict, and a merge should work every time
2) Look into why the desktop app thinks it made local changes instantly upon opening, even when no local changes have been made.

**Comment by KronosTheLate** [comment]
Still relevant. A lot would be fixed if one checked for conflicts before warning, and merging the changes if no conflict exists. I believe this would fix most issues.

However, it is still a problem that the desktop app appears to think it has made changes the moment it is opened, leading to the following behaviour: Any time I make a change on my phone, and then open the desktop app, I get a warning, despite having never changed files on two devices without syncing between.

**Comment by johannesjo** [comment]
Unfortunately I am unable to reproduce this. Do you also encounter this when syncing between super productivity desktop and the browser or the browser and the app run in another window in private browsing mode? If not this might be an android app specific thing.

**Comment by KronosTheLate** [comment]
I just updated the app, and recreated the folder sync connection. I think I had some bad state in my files, and also an older version of the app. Now, everything seems to be working smoothly for me.

I used the import/export buttons in the settings. Exporting a good state, removing the files in Dropbox, then importing and re-connecting to dropbox worked for me.
