### ISSUE TITLE
Local sync error (EPERM)

### ISSUE THREAD

**Issue by kaibrune** [johannesjo/super-productivity#2071]
### Discussed in https://github.com/johannesjo/super-productivity/discussions/2070

<div type='discussions-op-text'>

<sup>Originally posted by **kaibrune** May 12, 2022</sup>
Hi there,
I wanted to use the local file as a sync option but no matter which location is selected I'll get the error:

`Unknown Upload Errror (Settings correct?): Error: Error: EPERM: operation not permitted, open '/User/Documents/test.json'`

I guess this is to some permission issues (regarding macOS Catalina), but I don't know how to grand access. Thank you for your help and the great app!</div>

**Comment by kaibrune** [comment]
This is still a topic. :(

**Comment by johannesjo** [comment]
Hi there!

You can grant access via:
```
sudo chmod 777 /User/Documents/test.json        
```
Executed from a terminal.

**Comment by nikmak88** [comment]
In my MacOS Monterey it is fixed by `chmod 777` but this is not suitable if you have this file stored in a cloud synced folder, due to constantly have the privileges changed by the cloud sync agent to 700. So the files ends up rw only by me as owner and despite the fact that the app is ran by the same user and the App is registered in the settings to have full disk access, it needs 777. This needs a more permanent solution.

**Comment by johannesjo** [comment]
@nikmak88 I am open for suggestions.
