### ISSUE TITLE
Enable stoping ongoing task from another device

### ISSUE THREAD

**Issue by zoli** [johannesjo/super-productivity#2204]
## Problem Statement
I think it would be good if there was the possibility to start a task from for example desktop and pause it on android app. Currently it seems the sync doesn't save the data of ongoing task. 

## :grey_question: Possible Solution
There could be a ongoing task when saving data to sync which saves the beginning of time which the task has started. Then we can show the ongoing task on the other device.

**Comment by johannesjo** [comment]
Hey there! Can you explain this in a bit more detail?

What I understood is:
1. This should work through syncing as is (and not through a websocket or similiar)
2. That we use a special sync property (or new store property) to save the last tracking session started time for this to work

Problems I can see with this is, that there will almost always be a special sync conflict, since the desktop device is likely to continue writing updates, while the task is being tracked to.

**Comment by zoli** [comment]
Still relevant.
