### ISSUE TITLE
[Feature] Integration with Redmine system

### ISSUE THREAD

**Issue by loffa** [johannesjo/super-productivity#24]
Hi,

I would like to help with development of an integration system towards Redmine. I use that service at work but this app is a lot nicer and modern.

Would it be possible to build integrations to other platforms in an easy way?

**Comment by johannesjo** [comment]
Hello there! 

There are plans to implement a plugin system, so users can write their own integrations for other providers than Jira and GitHub. The problem is that that would require to rework a lot of things to provide an interface for plugins. I'm currently working on a ng2 version of the app (https://github.com/johannesjo/super-productivity2), where such things will be a lot easier. It's still very early in development unfortunately though.

Until then I'm always open for Pull Requests of course.
