### ISSUE TITLE
SupProd resets the pomodoro session for the reasons unknown

### ISSUE THREAD

**Issue by RZarifov** [johannesjo/super-productivity#2409]
### Your Environment

- Version used: 7.12.1 installed from AUR
- Operating System and version: Manjaro, 5.15 kernel
- Desktop Environment: i3wm
- Browser Name and version: ---

### Expected Behavior
The pomodoro timer is ticking, and doesn't restart.

### Current Behavior
Randomly, for the reasons unknown, pomodoro timer just restarts to zero, and it is surprising to see when you're like 20-ish minute in the session, it to restart back to zero, like you just started. Happened already like 4-5 times.

### Steps to Reproduce (for bugs)

Currently unknown. But if I catch something, I will let you know.

### Can you reproduce this reliably?
No.

### Logs
Logs are sent to the email. The title is the link to this issue.

**Comment by johannesjo** [comment]
Could you maybe also post your pomodoro settigns? That would be helpful!

**Comment by Xeizzeth** [comment]
Sure thing, here they are: https://i.imgur.com/onAXa1y.png

**Comment by Xeizzeth** [comment]
I have a hypothesis. Maybe SupProd does that when it syncs.  
Will try to catch that to confirm whether it's true or not.  
I sync via dropbox every hour if it matters.

**Comment by Xeizzeth** [comment]
Changed to every 5m.

**Comment by Xeizzeth** [comment]
@johannesjo Confiirmed. I just saw it with my own eyes. It resets the timer upon syncing. And also I must add that the timer didn't change the time regularly, in equal intervals. It was like "stuttering". Meaning the seconds change not each actual second, but the certain number could stay for more than a second, or, instead, less than a second.  
I suspect it's because the program struggled to keep updating the GUI for one reason or another.
