### ISSUE TITLE
[Feature Request]Don't break the chain

### ISSUE THREAD

**Issue by Cyber-Syntax** [johannesjo/super-productivity#2505]
Sometimes I struggled to study, but I experienced that this technique somehow helped to keep going without the need for motivation.

Anyway, I think this technique might be added to the work-log page, or maybe you can create a new page to deal with this habit tracking with the chain breaking technique.
Priority: Low

**Comment by johannesjo** [comment]
Do you intend this to be an extension of the simple counter feature or aimed at working every day?

**Comment by Cyber-Syntax** [comment]
I don't understand your point clearly but I think my intend is simple counter feature. 
Here is the my very simple project about that;
![image](https://user-images.githubusercontent.com/115875369/224382700-fd56aa69-8fe7-4f8a-b22b-d6071b1c9547.png)

**Comment by johannesjo** [comment]
What would be the advantage of integrating this over using a separate app for habit tracking?

**Comment by johannesjo** [comment]
Alright! Thanks for the explanation! I am not convinced we need this tbh unless there is a good way to integrate this into the other functionalities. There is a bit of feature creep going on as is :)

But of course if someone makes a good concept I might let myself be convinced otherwise.  

In any case: Thank you very much for the suggestion! :)

**Comment by kimjongbing** [comment]
> Alright! Thanks for the explanation! I am not convinced we need this tbh unless there is a good way to integrate this into the other functionalities. There is a bit of feature creep going on as is :)
> 
> But of course if someone makes a good concept I might let myself be convinced otherwise.
> 
> In any case: Thank you very much for the suggestion! :)

This would be a cool feature to track streaks on your habits. Since tracking habits usually entails that you do those habits everyday. So when you mark a "habit" (repeating daily task) as completed, it shows the amount of consecutive days you've completed the habit. TickTick has a feature like this so it'd be cool to have here as well.

**Comment by Cyber-Syntax** [comment]
I think that making it so small like GitHub's streak even can make a huge difference.
