### ISSUE TITLE
Bad habit counter for SuperProductivity

### ISSUE THREAD

**Issue by gelatinbomb** [johannesjo/super-productivity#2531]
## Problem Statement

This is just a little thing. I'm thinking of having a task for "bad habits". Something I can use to track if I have commited a bad habit. For now my idea is to have a task with sub task each indicating I commited a bad habit. The thing is the design of SP is really good and positive but it does not match the idea of my "bad habit" tracker.

## :grey_question: Possible Solution

Honestly just a little theme to indicate is a bad habit would be could, maybe an x instead of a check. We could go more deep and maybe a habit counter to SP would be cool. I have seen those on Habitica. You have a cross and a minus symbol. If you do something bad you click the minus icon and it adds you a negative point. Maybe with a text box to at least record what happen that might you cause to commit the bad habit.
## :arrow_heading_up: Describe alternatives you've considered

I mean there is habit trackers out there but having it integrated on SP would make things more easy.
## :heavy_plus_sign: Additional context

Not as far I know. Again this is just a little thing. For now I will use the normal task system to achieve my plan.

**Comment by Cyber-Syntax** [comment]
For now you can set a simple counter to handle that.

**Comment by JCKeanu** [comment]
A dedicated **bad-habit counter** would be a great addition to SP. Real productivity is not just about doing more – it's also about doing less of the things that silently sabotage deep work (doom scrolling, random tab surfing, etc.).

A simple counter per bad habit (with a negative trend indicator and an optional note per incident) would:
- make these micro-regressions visible,
- allow correlation with specific projects or time slots, and
- keep the whole reflection loop inside SP instead of requiring a separate habit-tracker app.

This would deepen SP's core strength by covering both the "do more" and "do less" sides of deliberate work.

**Comment by ryanpeach** [comment]
Something I think of more. There's a "did this" counter but not a "didn't do this" counter. Just a "no log" indication. Think the equivalent of a check mark vs a red x vs an empty circle. For "bad" tasks I want a red x on a "give up smoking" habit.

I think you might call these binary habits. Did/didn't is the binary, yes/no, whatever, with an indicator for "null" or "did not log"

Tap once to go from null to true. Then again from true to false. Then again for false to true. Delete goes back to null. Indicator graph shows -1, 0, and 1
