### ISSUE TITLE
GitHub backlog limited by 99 issues

### ISSUE THREAD

**Issue by murleo** [johannesjo/super-productivity#2748]
### Your Environment

- Version used: 7.3.12 (just updated), used 7.3.11 most of the time
- Operating System and version: Windows 10 Pro 22H2

### Expected Behavior

After importing GitHub repository with more than 100 issues (it has 132 open issues) I am able to search for any existing open issue or newly added one.

### Current Behavior

Backlog imported 99 issues and doesn't import new ones. Neither auto-completion of "Add new Task" nor sync to backlog let's me track progress for newly added issues to GitHub.

I used to add single issues when needed using "Add new Task" button. Auto-complete was proposing issues from GitHub. It worked great and tracked ~150 hours so far. A few days ago I enabled "Automatically add unresolved issues from GitHub to backlog" and I am stuck with some 99 issues. Is it possible to clear the local backlog to mitigate the issue?

The reason why I tried enabling "Automatically add unresolved issues from GitHub to backlog" because auto-completion of "Add new Task" doesn't work reliable and often returns nothing. I think this is because of 'encodeURIComponent'. With 'encodeURI' the same URL returns results. #2749 

Thanks!

**Comment by johannesjo** [comment]
Hey there! It's the github api that limits its responses to 100 items (there would be ways around this by making multiple requests, but this comes with some other complications/costs). Super Productivity always pulls the last 100 but requests them ordered by updated (for the auto import to backlog). It's weird that the issues don't show up when using the search since that directly uses the github api. Maybe you can use the dev tools (ctrl+shift+i and then navigate to the network tab) to figure out what goes wrong?

**Comment by cuberleon** [comment]
I only tried to use backlog feature once and stopped using it because of the amount limit. However, it's no longer a problem for me because the search suggestions work again :) I built a custom binary that includes https://github.com/johannesjo/super-productivity/pull/2750. Thanks!
