### ISSUE TITLE
A possible improvement

### ISSUE THREAD

**Issue by VladRoscaDev** [johannesjo/super-productivity#275]
**THE CASE**
I noticed that to get the app to log you work time you have to mark the task as done.
Sometimes there are tasks that take more than one day to finish because of poor planning. 
Therefore i suggest that the app can log you work automatically in Jira after you hit the Finish Day button.(I noticed that it doesn't do this now)
It would be a very helpful feature.

If needed I can help on this topic. Thank you for the great software and making things easier for all of us!

**Comment by johannesjo** [comment]
Thank you for the suggestion! 

I thought about a similar concept before, but to be honest I am a little bit afraid about all the work it might cause, as
1. Date stuff can get messy
2. It's not easy to communicate to the user what is going on
3. There are possibly lot's of possible edge and special cases to consider (what happens when the user changes the time spend manually later on, just to name one)

I am open to let myself be convinced otherwise though :)

**Comment by VladRoscaDev** [comment]
Well for the issue your talked about for the moment I would leave it as it is. But this one has to do with the process of automatization of the stubbern task of logging your work, that could be done by using the same method as if I were to mark it as done. This is a pritty common pattern and in my opinion it would be very nice to have.

**Comment by johannesjo** [comment]
As this probably won't happen, I am closing this. Thank you very much for your suggestion, though.
