### ISSUE TITLE
Mac App Store version is really outdated

### ISSUE THREAD

**Issue by pow-nico** [johannesjo/super-productivity#2789]
### Your Environment

- Version used: 7.11.5
- Operating System and version: MacOS 11.7.10

### Expected Behavior

current GitHub version 7.14.3 should be provided via the Mac App Store

### Current Behavior

version provided is a very outdated one 7.11.5

### Steps to Reproduce (for bugs)

1. open list of recent releases: https://github.com/johannesjo/super-productivity/releases
2. click on App Store icon
3. install and download app
4. check in app settings for version number

### Can you reproduce this reliably?

yes

**Comment by johannesjo** [comment]
Hey there! In the past the mac releases have required a lot of effort mainly due to the release process for electron apps being so complicated. Given that there are only a very small number of users, using the mac store version (below 60) the amount of work going into it is not really justified at the moment. 

This being said: If I happen to have more time in the future I might give it another shot. :)

**Comment by pow-nico** [comment]
Ok, good to know and thank you for the answer. 👍

**Comment by johannesjo** [comment]
The version should be up to date again :)
