### ISSUE TITLE
Logseq integration

### ISSUE THREAD

**Issue by Talleyrand-34** [johannesjo/super-productivity#2871]
## Problem Statement
There is no way to manage tasks in logseq

## :grey_question: Possible Solution
Create a plugin to integrate with logseq

## :arrow_heading_up: Describe alternatives you've considered
I'm not sure which is the solution

## :heavy_plus_sign: Additional context
I'm a computer engineer and need this functionality, but also im a newbie and i don't know how to approach this problem. 

## Inspiration
https://github.com/hkgnp/logseq-todoist-plugin

**Comment by l3ocifer** [comment]
i don't know how to do this either, but I'd love to sync this up to my logseq, so I'm game to help if we can figure out a plan.  Best guess is....a plugin, like you mentioned for todoist.  guess we should learn how to make a plugin

**Comment by Tursu311** [comment]
I don't like to-do organization in Logseq, so I want this functionality too.
Agree best will be a Logseq pluguin, maybe we should move to Logseq issues?
I think first step could be try to understand how todoist plugin works and possibly make a fork?
I think Superproductivity works with single json and Logseq many .md.
But first I think we should explain what we actually want, Logseq TODO to be synced to Superproductivity or something else?
Also, I'm a newbie, but I could help a bit in the development.

**Comment by Demorome** [comment]
With the advent of the official "Sync.md" plugin, a standalone plugin for Logseq integration may no longer be needed.

One could simply set up a page/file in Logseq that contains a perpetually-updated list of all tasks, and let the Sync.md plugin take care of the rest.

Logseq's `/query` functionality seems perfect for this, however the results are never saved to the .md file; only the query is saved, example: 
```md
- {{query (task CANCELED TODO NOW LATER DONE DOING IN-PROGRESS WAITING CANCELLED WAIT)}}
```
So all we'd need is some functionality built into Logseq to perpetually maintain a query file, as well as automatically backporting task changes from that task-query file to the actual blocks where those tasks reside.

I'm not sure how to set this up, however.
There could be a simpler way I'm missing, since I'm new to Logseq, but one idea would be to rework/extend the https://github.com/benrhughes/logseq-query-export plugin to auto-export a task-query as a Markdown task-list file every so often.
However, this doesn't solve the problem of backporting changes made to that task-list file (likely as a result of changes coming from SuperProductivity, thanks to Sync.md plugin).

I suppose a much more complicated plugin setup that keeps track of which file and line number a task block was found in would be needed for that second functionality.

Not to mention complications due to Logseq being fragmented with a new DB version.
