### ISSUE TITLE
Error: Project INBOX not found

### ISSUE THREAD

**Issue by nabil-aitsaid** [johannesjo/super-productivity#2950]
### Steps to Reproduce

1.click on Settings
2.set the Darkmode to Dark
3.
4.

### Stacktrace
```
Error: Project INBOX not found
    at file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:320418
    at file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:4140131
    at $r (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:4139651)
    at gn (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:4140564)
    at file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:4140188
    at $r (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:4139651)
    at v.project (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:4138994)
    at v._next (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:3824517)
    at v.next (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:3812646)
    at Ne._subscribe (file:///snap/superproductivity/1827/resources/app.asar/dist/main.407166d2fd5c3e92.js:1:3805401)
```

### Meta Info
META: SP7.17.1 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.17.1 Chrome/120.0.6099.109 Electron/28.1.0 Safari/537.36

### Actions Before Error
```
1703808302921: [Idle] Set idle time 
1703808303688: [FocusMode] Set focus session elapsed time (2) 
1703808303921: [Idle] Set idle time 
1703808304688: [FocusMode] Set focus session elapsed time (2) 
1703808304922: [Idle] Set idle time 
1703808305688: [FocusMode] Set focus session elapsed time (2) 
1703808305923: [Idle] Set idle time 
1703808306688: [FocusMode] Set focus session elapsed time (2) 
1703808306923: [Idle] Set idle time 
1703808307188: [FocusMode] Set focus session elapsed time 
1703808307688: [FocusMode] Focus session done 
1703814056567: [Idle] Set idle time (5746) 
1703814057124: [Idle] Dialog result 
1703814057127: [Idle] Reset break timer 
1703814057127: [Tag] Update Break Time for Tag 
1703814057129: [Idle] Reset 
1703814057130: [Persistence] Save to DB 
1703941852499: [FocusMode] Set focus session elapsed time 
1703941852571: [SP_ALL] Load(import) all data 
1703941852572: [SP_ALL] All Data was loaded 
1703941863929: [Layout] Toggle SideBar 
1703941873837: [Global Config] Update Global Config Section 
1703941873865: [Persistence] Save to DB 
1703941887165: [FocusMode] Set focus session elapsed time 
1703941887229: [SP_ALL] Load(import) all data 
1703941887235: [SP_ALL] All Data was loaded 
1703941899158: [Global Config] Update Global Config Section 
1703941899161: [Persistence] Save to DB 
1703941905653: [FocusMode] Set focus session elapsed time 
1703941905720: [SP_ALL] Load(import) all data
```

**Comment by harshgupta246** [comment]
Was facing the exact same problem, despite the latest commit, found a simple work around. I am using the Webapp version. (Possibly, because I had backed up - after getting the error).

**Description**: There is an error (Error: Project INBOX not found) popup that hinders the ability to see and work with the app, but the app still works in the background, if you zoom-out. 

**Work around**: I was able to solve this problem by replacing "DEFAULT" project with "INBOX" in backup file and then import it back in the webapp. 

1. First zoom-out, so the error box reduces in size.
2. Go to settings &rarr; Sync & Export &rarr; Import/Export &rarr; Click on export data.
3. Make a copy of this file (just in-case things go wrong).
4. A json file will be downloaded. Open it using a text editor. (You might need to use a formatter to make it readable).
5. There should be a "DEFAULT" project, existing. Renaming this project to "INBOX" or creating an additional empty project with id "INBOX" should work. (Use find-replace to do this).
    <ul>
    <li>You need to add/ replace INBOX in project.ids & project.entities (in-case of creating an empty "INBOX" project, you will 
           need to add all the options and structure to the project.entities as well)
    <li> If you are replacing "DEFAULT" project, make sure to check globalConfig.misc.defaultProjectId as well. If it is set to 
           "DEFAULT" - replace that to INBOX as well or set it to false (incase you don't want any default project).
    </ul>
6. Go to settings &rarr; Sync & Export &rarr; Import/Export &rarr; Import from file &rarr; Select your file.
In-case, something happens, you can always import the backup file to make sure all your tasks are safe.

Lastly, if this is the wrong place to put this out, kindly let me know. I am still new to open source.

Love using this app. I am still learning and hope to contribute here one day. Thanks !

**Comment by johannesjo** [comment]
Does this issue also occur with the latest v7.17.2 release?

**Comment by harshgupta246** [comment]
Just recreated the error using older backup file,can confirm Meta Info says SP7.17.2

**Comment by johannesjo** [comment]
Thanks for confirming @harshgupta246 !! It would be great if you could share a (anonymized) copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by harshgupta246** [comment]
Hi @johannesjo just sent you an email as per the provided email address with the requested data. Let me know if you have received it.

**Comment by johannesjo** [comment]
Thank you very much! This should be fixed with the next release!
