### ISSUE TITLE
Tasks absent in timeline

### ISSUE THREAD

**Issue by one3711** [johannesjo/super-productivity#3085]
The tasks added for the day aren't all added to the timeline.

**Comment by johannesjo** [comment]
With the information given I am unable to reproduce this. Can you be a bit more specific?

**Comment by one3711** [comment]
My bad. I added the tasks in a specific project and expected them to be automatically added on the timeline. I didn't know you've add add them on 'Today'.

**Comment by Jagdfalke** [comment]
Well, in fact there are two ways to add tasks to the timeline. One way - as you mention - is to add the tasks to 'Today'. This is helpful to see how your tasks flow around the day. 

The other way to add tasks to the timeline is to schedule them at a specific time and day.

**Comment by one3711** [comment]
Ok, got it! Scheduling to a specific day will work better in my case.

**Comment by nairboon** [comment]
I was just asking myself the same. Maybe the timeline feature creates an expectation that all the tasks should show up, not only today, but also in the future days.  
In case anyone else was asking the same, the issue is that there is currently no deadline time for a task, which would be needed for such an automatic scheduling for all tasks. See also #405
