### ISSUE TITLE
Support of client certificates for JIRA integration

### ISSUE THREAD

**Issue by digitalkram** [johannesjo/super-productivity#3119]
## Problem Statement
Setting up "JIRA integration" fails when the JIRA instance requires a client certificate to establish the TLS connection to the JIRA instance.

## :grey_question: Possible Solution
Offering the option to specify a client certificate when setting up the JIRA integration (and make use of it) would probably help.

## :arrow_heading_up: Describe alternatives you've considered
I am not allowed to proxy or circumvent this security measure by any means so even if there would be an alternative approach I would not be allowed to make use of it.

## :heavy_plus_sign: Additional context
It is a corporate instance so that's why it is so locked down.

## error log
```
10:32:35.341 › Frontend Error: {
  HANDLED_ERROR_PROP: {
    HANDLED_ERROR_PROP: 'Jira: request to https://<censored>.com/rest/api/latest/myself failed, reason: write EPROTO 67430987123136:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 40\n'
  }
} null
```

**Comment by Jagdfalke** [comment]
Thank you for your request. This is probably a tough one to implement due to how different platforms handle certificates and private keys. The latter also makes this a sensitive topic. 

For your specific use case, can you provide more detail around how the certificate is usually handled? Is my assumption correct that this is a personal certificate that not only establishes a secure connection but also authenticates you as a user?

Are you provided with a pfx or pem file for you to install the certificate yourself wherever you want? Or does your certificate come preinstalled with your browser? Or is the certificate in the operating system's keystore?

**Comment by digitalkram** [comment]
@Jagdfalke Thanks a lot for taking the time to comment in detail. That's very much appreciated 😊

At least for the way it is handled in my scenario the target platform (as in jira, github (enterprise), etc.) does not matter. It is indeed a personal certificate but this is only used for the tls connection. Authentication is totally independent and in my case implented by a (proprietary) oidc-compatible idp that is used across a wide range of applications throughout the company.

The certificate comes pre-installed in the OS keystore and the Firefox keystore. However we can download a pfx as well that I previously used to import it to other devices and a jvm keystore (for some Java-based applications that need to access jira).

**Comment by Jagdfalke** [comment]
@digitalkram Thank you for your feedback and the details you have provided.

To be honest, this is a niche requirement at the moment. So it is unlikely to happen very soon unless someone is willing to tackle it. So help is very welcome!  🙂
