### ISSUE TITLE
Cannot add names in subtasks   - WINDOWS11

### ISSUE THREAD

**Issue by Jota-veh** [johannesjo/super-productivity#3258]
![peek_1](https://github.com/user-attachments/assets/82c0d9b5-a849-4cb8-9f40-78668237b73d)

**Comment by spotman** [comment]
I'm experiencing the same issue on web, android and desktop apps. BTW several days ago subtasks were working properly.

**Comment by johannesjo** [comment]
Do your devices have a touchscreen by any chance?

**Comment by spotman** [comment]
> Do your devices have a touchscreen by any chance?

Yep. iOS 13 tablet (web version) and Android 9 phone (native app).

**Comment by Jota-veh** [comment]
> Do your devices have a touchscreen by any chance?

yes, but on linux this won't happen with the same device. only on windows

**Comment by johannesjo** [comment]
The problem is likely that the app is getting some wrong information about what your primary device is. If you open the console (Ctrl+Shift+i) you will see what input device is detected. Should be the very first entry and look like this `{IS_MOUSE_PRIMARY: true, IS_TOUCH_PRIMARY: false}`. I am afraid that if a touch is detected as primary device the only way around this is to disable touch on windows completely.

**Comment by johannesjo** [comment]
While we can't directly fix this, maybe there are some ways to optimize this. I am open for suggestions to make the UI work better for touch and mouse at the same time.

**Comment by Jota-veh** [comment]
well.... if there is an update and an option to choose my device as a touch or not touch, that would made the trick, i think

**Comment by johannesjo** [comment]
There are some changes planned for the next release. Please let me know if it works better then for you.
