### ISSUE TITLE
[Feature Request] Archive Project in version 5

### ISSUE THREAD

**Issue by Jackymancs4** [johannesjo/super-productivity#331]
Hello @johannesjo ,

This issue is meant as a follow up of #104 , in order to track the efforts (or intentions) to bring back this feature.

For reference, I see here

https://github.com/johannesjo/super-productivity/blob/59e2a19f2140be6c315a2e3f41e8300fc0c9ccff/src/app/pages/project-overview-page/project-overview-page.component.html#L41-L54

that all archive-related code has been commented out, and this commit https://github.com/johannesjo/super-productivity/commit/41166e765bff4982cf46de02e3b3e04fa90f013c message says that it's most likely a temporary change.

**Comment by johannesjo** [comment]
Thanks for opening this up. I currently intent to bring back the feature. Not sure when this will happen though as there might be another big model change coming up, because I'd really like to improve syncing to make a hybrid usage with mobile more viable.

**Comment by mcorossigo** [comment]
Hello @johannesjo 
I'm starting to pile up projects that I finished and will (most likely) not recieve new tasks anymore.

I'm using manual sorting to keep those projects down the list, but the sidebar is crammed now, and I have to scroll every time to reach the Tag section.

May I know your thoughts on this?

I tried to take a look at this, but your codebase is pretty big!

Anyway, thank you!

**Comment by johannesjo** [comment]
@mcorossigo I definitely see how it might be useful. For most people it would be probably enough to hide them from the list, rather than really archive it. This should be pretty doable. The relevant stuff should be located here:
https://github.com/johannesjo/super-productivity/tree/master/src/app/features/project
https://github.com/johannesjo/super-productivity/tree/master/src/app/pages/project-overview-page
https://github.com/johannesjo/super-productivity/tree/master/src/app/core-ui/side-nav

All needed is a new boolean field for the project, to check whether it is archived or not. If it is than we hide it from everywhere with the exception of the project overview page, where it can be restored.
