### ISSUE TITLE
Allow on premise gitlab instance (selfhosted gitlab)

### ISSUE THREAD

**Issue by fulljackz** [johannesjo/super-productivity#337]
### Your Environment

* Version used: latest debian package : 5.0.10
* Operating System and version: Ubuntu 20.04
* Desktop Environment: Gnome-Shell 3.36

### Expected Behavior
- When I had a project, I can setup gitlab integration just by setting username/project
- It could be awesome if we could use a custom gitlab url

### Current Behavior
- Instead a username/project, we should add full url. 
- If full url is not written, just try to match username/project string

**Comment by johannesjo** [comment]
Thanks for opening this up!

@MostafaAmin07 can I assign this issue to you?

**Comment by fulljackz** [comment]
I am currently trying to have a kind of patch but I dot not know at all languages used in the project.
For the moment I just tried to hardcode my self hosted gitlab instance and I am trying to build.
If it works as I expect, I will try to match if input is "full.url/project/username" or "project/username".

If it works (what I do not really expect :)), I will push a MR.

Regards,

**Comment by johannesjo** [comment]
@fulljackz That would be awesome!! You should be able to find all relevant stuff here:
https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers/gitlab

For development please follow the instructions in the readme.

**Comment by fulljackz** [comment]
News from the front.
I just checked the code in `gitlab.const.ts` and change the `GITLAB_API_BASE_URL` to mine.
I just build and try to run the app and it's working !
I can poll issues from my gitlab instance and I can view them in the webapp.

The next question is (and I think what the answer is) : is it possible to push issues from super-productivity to gitlab ? It would be a powerfull thing !

**Comment by johannesjo** [comment]
You mean to create new issues from the app? Not yet, but we should make it a feature :)

**Comment by fulljackz** [comment]
Yes, a kind of bidirectionnal way.
I think that a full "interface" with gitlab should be pretty cool :
- issue create / close
- interactions with time tracking functions into gitlab
- push comment into issue 

If it has a sense for you or others, do we have to create an issue for each ?

**Comment by johannesjo** [comment]
Makes sense to me to have something like this (I am certainly not against it), but I think it is hard to figure out the right way to do it. You don't want issues to be created or updated accidentally as Super Productivity messing up your teams Scrum Board could potentially be embarrassing. Because of that this should be kept as simple and unsurprising as possible :)

**Comment by willhseitz** [comment]
> I will try to match if input is "full.url/project/username" or "project/username".

@fulljackz Instead of trying to match on full URL vs just project/username, why not just add a check for "use custom URL", that when selected, shows a field to enter a hostname of the custom gitlab instance?

**Comment by b0c1** [comment]
I try to add my gitlab url but It's not work. My project URL is deep: https://internal.host/gitlab/group1/group2/group3/project.

I see in the debug console it's  rewritten to https://internal.host/api/v4/projects/gitlab%2Fgroup1%2Fgroup2%2Fgroup3%2Fproject/issues 
I know you want to solve with one URL but why? Why not 2? I mean first is the base URL (ex: https://gitlab.com/ or https://internal.host/gitlab/) and another to the project.

I think it's a fast and simple solution instead of "try to find the base URL and then the API"

**Comment by johannesjo** [comment]
Thanks to @b0c1 this should work starting with the next release (or with the current edge channel release).

**Comment by toxsick** [comment]
Hey guys, I just checked this out and it is working as expected with our self-hosted gitlab instance.

I have a question though. The times tracked in superproductivity are never synced back to the gitlab issue right?

This would be a killer feature!

regards
Hannes

**Comment by johannesjo** [comment]
@toxsick thanks for reporting back and thanks again @b0c1 for implementing this!

For time tracking with GitLab instances we should open up a new issue (if there isn't already one).
