### ISSUE TITLE
Unable to sync to NextCloud

### ISSUE THREAD

**Issue by sdcaulley** [johannesjo/super-productivity#3555]
### Your Environment

- Version used: 9.0.7 (.deb)
- Operating System and version: Linux Mint Debian Edition 6 (faye)
- Desktop Environment: Cinnamon v 6.2.9
- NextCloud version: Nextcloud Hub 8  (29.0.4)

### Expected Behavior

To sync to my my NextCloud instance

### Current Behavior
![image](https://github.com/user-attachments/assets/bfe7cf84-f175-41be-a5b8-55ec10d9b27f)

![image](https://github.com/user-attachments/assets/8a4ecc6f-fb66-4e9e-b555-317bcd90b06e)

### Steps to Reproduce (for bugs)

1. Filled out the fields in the proper Settings section
2. Created a directory on NextCloud
3. Press the sync 
4.

### Can you reproduce this reliably?
This is happening consistently.

### Console Output

Using desktop app, so not applicable

### Error Log (Desktop only)

<!--- For the desktop versions, there is also an error log file in case there is no console output.
Usually, you can find it here:
```
[2024-10-07 12:23:18.446] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-10-07 12:23:18.642] [info]  Saving backups to /home/stephanie/.config/superProductivity/backups
[2024-10-07 12:23:19.416] [info]  No custom styles detected at /home/stephanie/.config/superProductivity/styles.css
```

**Comment by kkoyung** [comment]
@sdcaulley 
I guess your nextcloud is not under subpath `/nextcloud`. Remove `/nextcloud` from the base url, and try again, i.e. use `https://example.com/remote.php/dav/files/stephanie` as the base url. (Remember to replace `example.com` with your nextcloud domain name.)

If it is still not working, go to the "Files" app on your nextcloud, in your browser. 
1. Click "Files settings" at the bottom of the left sidebar. (If the left sidebar doesn't appear, click the three-line-icon below nextcloud logo on the top-left corner.)
2. Copy the "WebDAV URL".
3. Use this url as the base url in super-productivity.

**Comment by sdcaulley** [comment]
@kkoyung That worked for the desktop sync, but I am still getting an error on Android.  

![signal-2024-10-13-070826_002](https://github.com/user-attachments/assets/793e34db-1a0d-46a2-b343-5bbe04b14893)
![signal-2024-10-13-070826_003](https://github.com/user-attachments/assets/ab5a6efe-7b88-4f79-aaa3-23325d1af0bb)

**Comment by kkoyung** [comment]
@sdcaulley 
Assume the "Sync Folder Path" in the super productivity settings is `super-productivity` as default. Before synchronizing from Android app, you may first manually create a folder called `super-productivity` in your nextcloud account, or first synchronize from your desktop so that there will be a `super-productivity` folder in your nextcloud. This may help.

---

@johannesjo 
I mentioned in a note of my previous PR (https://github.com/johannesjo/super-productivity/pull/3534#issuecomment-2392884795) that error may occur if the target directory does not exist. The situation may be slightly more complicated than I thought.

When the target directory for `MAIN.json` and `ARCHIVE.json` does not exists, Nextcloud gives 404 response on the PUT requests. Then, the desktop version of super productivity send a PROPFIND request and a MKCOL request to create the directory. After that, it send the PUT requests again. So, it successfully synchronizes the data.
![screenshot_2024-10-14_00:02:09](https://github.com/user-attachments/assets/97992fc1-abc0-4a82-b4e3-e1fd27d1dd1c)

However, the Android version of super productivity does not send the MKCOL request to create the directory.
![screenshot_2024-10-14_00:01:23](https://github.com/user-attachments/assets/89da6e05-4ec8-45d1-a7be-df567461317b)

Furthermore, different webdav server give different response on this situation. For example, Nextcloud simply gives 404 response but apache gives 409 response. This results in different behavior of super productivity in different platform. 

This could be resolved by simply adding a mechanism to check the existence of the target directory and create it if it does not exist, before the current synchronization process.

**Comment by sdcaulley** [comment]
@kkoyung There is a directory on NextCloud and the desktop app is syncing to it, but the android app still claims there is nothing there.

**Comment by kkoyung** [comment]
@sdcaulley Try `https://example.com/remote.php/dav/files/stephanie/` **with** the trailing slash.

**Comment by sdcaulley** [comment]
@kkoyung New error now, a 409 conflict.

![Screenshot_2024-10-14-11-09-19-45_f4e243341759c1045d9d9d3a2b41a256](https://github.com/user-attachments/assets/f5c1f9d1-e9b7-474a-8c72-74c3a48b6d3b)

**Comment by kkoyung** [comment]
@sdcaulley That's weird. I cannot replicate the 409 error on my device. Can you show me your settings on Android? Are they exactly same as the one using on your desktop?

**Comment by sdcaulley** [comment]
@kkoyung It is working now. Found a typo on the screen shot. Thank you for all your help.
