### ISSUE TITLE
Setting time for reminder caused bluescreen on Win10, doesn't boot anymore

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#358]
I just downloaded Super Productivity from Microsoft Store to explore the features, using Windows 10. I changed the language to German and tested some project settings like changing colours etc. When setting the time for the first task, Super Producity freezed and caused a bluescreen. Now i can't boot the PC. and even all recovery and reset option cause errors. What happened and what can be done about it? (I'll provide additional info, if you can tell me where to find it)

**Comment by johannesjo** [comment]
I am very sorry to hear that. It is highly unlikely that the issue is specific to Super Productivity. It could be either an electron bug or related to something else going on on your system.

What error message was printed on the blue screen. That's crucial to resolve your issue I think.

https://github.com/electron/electron/search?q=bluescreen&type=Issues

**Comment by halloichbingunnar** [comment]
I'm afraid I didn't take a note during the bluescreen (whoopsie). Now it's a d000014c during recovery attempts, but I guess that's not too helpful? If there were no reported issues before, it may just be a hardware issue not related to super productivity... I called the PC manufacturer's support for a check. Thanks for your help anyways 🙃

**Comment by halloichbingunnar** [comment]
ah, and the initial error referred to "missing locale "de" for the time setting and happened in 5.1.0 :)

**Comment by johannesjo** [comment]
d000014c seems to refer to some boot files missing. Sounds serious, but makes it seem even more unlikely that the issue is caused by the app. 

Really sorry about the issue. I know from a lot of experience that an unbootable PC can suck very hard.

If you ever figure out the cause, please let me know!
