### ISSUE TITLE
[Bug] New project clones last project

### ISSUE THREAD

**Issue by Morganamilo** [johannesjo/super-productivity#41]
## Your Environment

* Version used: v1.6.7 e3928b4 deb
* Operating System and version: Arch Linux 4.13.9-ck
* Desktop Environment: i3

## Expected Behavior

Create project should always make an empty project (i think, this could be intentional)

## Current Behavior

Creating a project always clones the project that was made last

## Steps to Reproduce (for bugs)

1. Create project
2. Add tasks
3. Create new project
4. Those tasks are copped into the new project

It always clones the project created last, so even if you switch projects it will still clone the last one. Not one you're currently using.

Also a side note, "Save current todo as project" with no project title brings up a toast notification "Project undefined successfully saved" but nothing actually happens. Wasn't sure if this deserved its own issue.

**Comment by johannesjo** [comment]
If you like to dive into the mess, this are the two files mainly responsible for handling project related stuff:

https://github.com/johannesjo/super-productivity/blob/develop/app-src/scripts/main/global-services/projects-s.js

https://github.com/johannesjo/super-productivity/blob/develop/app-src/scripts/main/global-services/app-storage-s.js

Otherwise the  fix has to wait until after I'm back from vacation ;)

**Comment by Morganamilo** [comment]
I'll have a look into it at some point maybe, I only really know vanilla JS though. electron and all that is a bit above me.
