### ISSUE TITLE
Add reminders feature

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#446]
As discussed here #441

Original Title: "Add optional reminder for prioritization (and maybe other stuff)"

The idea is to have a generic reminder interface for little messages that can be displayed as snack, alert, banner and/or system notification.

**Comment by johannesjo** [comment]
Still relevant.

**Comment by daya** [comment]
Yes this is relevant for many scenarios of reminders

**Comment by daya** [comment]
I think it is still relevant.

Obviously reminders will also need to be supported with either snoozing reminders or rescheduling tasks for which reminder popped up.

**Comment by ashutoshsaboo** [comment]
Hey @johannesjo ! This would be really incredible if it can be implemented, i've been trying to search for a local-only privacy-first todo app since long haven't found any better alternatives than super productivity. The only major con is lack of reminders on mobile apps especially (but desktop apps too), as system notifications. Any plan if this would be implemented soon? Happy to help out for beta testing, if in case that's needed.

**Comment by ashutoshsaboo** [comment]
Still relevant

**Comment by ashutoshsaboo** [comment]
Still relevant

**Comment by ashutoshsaboo** [comment]
Still relevant

**Comment by ashutoshsaboo** [comment]
Relevant
