### ISSUE TITLE
[Feature Request] Move sub tasks individually

### ISSUE THREAD

**Issue by theCalcaholic** [johannesjo/super-productivity#476]
It would be a great improvement for many work flows to be able to move sub tasks separately from each other. Otherwise, very large parent tasks (i.e. on a strategic goal level, or on a (big) feature level) are still not really an option, because they will clutter my active tasks list for weeks or months and I can't prioritize (reorder) them individually. Therefore I usually fall back to mark sub tasks by their title (e.g. "parent -> sub task").

**User Story**
Given I have a parent task with multiple subtasks, I, as a user, want to be able to have all of the subtasks except for one in my backlog - because an important motivation for splitting tasks in the first place is not working on all of them at once and if it's not in my backlog, I'm (supposed to) actively work on it.

Moving sub tasks separately would also enable me to arrange them individually in my task order (e.g. to manage priority/importance)

Visually, there would be a variety of options for this - a sub task could display the parent task's title in its own title bar (and maybe be linked?); all sub tasks could still come with a wrapper box like it is now (there would be multiple per parent task) or (the parent task could be displayed  in another UI element, e.g. a side bar or a separate column.

For reference, if I have subtasks of the same parent task in both the backlog and other stages in JIRA it looks like this:

![grafik](https://user-images.githubusercontent.com/6317548/89404369-23533a80-d71a-11ea-97ea-ba47adcfc39b.png)

**Comment by johannesjo** [comment]
Thanks for opening this up as a new issue. Makes a lot of sense as there might be a lot of discussing to do :)

Unfortunately separating sub-tasks from a parent raises a ton of problems, as the distinction between those two is important on many levels. But I definitely can see that this is a problem and I encounter it for myself every once in a while when I am working on a task which spans multiple days. It would be nice to have some way to remove the previous clutter when continuing on another day. 

I can see two directions (though there might be more and I am happy for any suggestions!):
1. We add a split parent task feature which allows to split up its subtasks to move the undone ones to a new one
2. We allow separating sub-tasks by tags, but always keep the reference (we can't subtasks have subtasks or make them repeatable for example). This will complicate things quite a bit on many levels, because we effectively add another task type.

I don't have a good solution or final opinion on how to best deal with this all. Just wanted to spell it out, so maybe we can come up with another solution or some adjustments  that don't add so much complexity.

**Comment by theCalcaholic** [comment]
Hm, maybe I have another idea...
The main issue is having sub tasks spread across backlog and active tasks. A possible way to approach this would be to let me move a subtask to active tasks, keep the reference to it's parent and show it both in the backlog and in the active tasks list.

That shouldn't add too much complexity and would solve the main issue.

The backlog display of the parent task could be read-only (maybe highlight the task in the active tasks list when you click on it).

E.g. like this:
![sp_split_subtasks_concept](https://user-images.githubusercontent.com/6317548/89514610-5eb33f00-d7d6-11ea-99f9-1a3d29244cc7.png)

**Comment by johannesjo** [comment]
That's a very interesting suggestion! I've to think about it.

**Comment by johannesjo** [comment]
Just wanted to say, that I haven't forgotten the issue. It's just that I currently have only a very limited amount of time available each week and there is so much else to do...

**Comment by johannesjo** [comment]
Still relevant.
