### ISSUE TITLE
Some Tasks Are not Repeating.

### ISSUE THREAD

**Issue by PannenetsF** [johannesjo/super-productivity#513]
I have searched the issues.

### Your Environment

* Version used: Appimage 5.6.2
* Operating System and version: Manjaro Linux 5.7.14-1-MANJARO
* Desktop Environment:  KDE5

### Expected Behavior
Any tasks could repeat with no problem.

### Current Behavior

Some tasks(not all tasks!) will not repeat even I checked the `repeatCfg` in .json. Then I checked its UNIX timestrap in `taskRepeatCfg->entries->xx->lastTaskCreation`, the last creation is yesterday and it should repeat today.

My machine learning and some else task get this error
```json
"RQcihva8R": {
                "lastTaskCreation": 1598322621218,
                "title": "ML",
                "projectId": "XeVn1SCxU",
                "monday": true,
                "tuesday": true,
                "wednesday": true,
                "thursday": true,
                "friday": true,
                "saturday": false,
                "sunday": false,
                "isAddToBottom": false,
                "tagIds": [],
                "id": "RQcihva8R"
            },
```
But there are still some normal tasks able to repeat.

### Steps to Reproduce (for bugs)

I have tried, but there is just not a common way  to reproduce.. If the task is named 'ML' again, and it will fail again, too. If 'Typing', it's okay.

So I have get my backup in to a gist. [backup](https://gist.github.com/PannenetsF/7b2394d513f7294c271b1363d21af433)

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting (in such a nice fashion with all the data I should need ;))! I'll look into it as soon as I can.

**Comment by johannesjo** [comment]
Hey there! I just checked your data. I didn't dive too deep to be honest but it seems to work as expected for the most part (apart from a wrong id for a task, but I guess that's due to a copy&paste error). 

How repeatable tasks are working right now, they're recreated when:

1. You navigate to project (or start/restart the app)
2. And when today is one of the weekdays selected for that task
3. And when there was no instance of that task yet created for the current day. This includes done tasks

So looking at the list, it seems like the task is not re-created, because there are still instances active, which have not been yet moved to the task archive (by finishing your day...).

Not sure if this is the best behavior for this feature and I am open to improvement suggestions.

**Comment by PannenetsF** [comment]
Thanks for your time and patience! 

I am sure that 
1. I close my app after a day's work and reopen it the other day. 
2. I finish my due task every day.

So I am also confused that some just not repeat. Now I just reopen the app again because it 1:15 am in China every due task will repeat. But the CSAPP task just do not appear. I  think it may help that I delete the repeatcfg for CSAPP via the app and then.create a new one. 

The json error may happen during a crash in #499 and crash continued after reload so I import the backup of that day(not yesterday of.that day). 

Thank you for your help!

**Comment by johannesjo** [comment]
I just checked. If I do the following:
1. Fix the broken task as commented on the gist
2. Navigate to 2020Summer
3. Click ' Finish Day'
4. Click 'Save and go Home' 
5. Navigate to 'Today' 
6. Navigate back to '2020Summer'

'CSAPP' is recreated.

**Comment by PannenetsF** [comment]
Thanks for your advice and I have fixed my problem!
