### ISSUE TITLE
hyperlink from downloaded Jira issues does not work, do I need to do anything special to get it to work?

### ISSUE THREAD

**Issue by tustinn** [johannesjo/super-productivity#551]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Hi there! What do you mean by does not work? And which link exactly?

**Comment by tustinn** [comment]
clicking on Summary link takes me here:
https://my-server.atlassian.net/browse/14718

link within Jira itself is:
https://my-server.atlassian.net/browse/CP-4719

![image](https://user-images.githubusercontent.com/23008966/94712760-c2517880-02fe-11eb-9d9a-8ed9c75a5da4.png)

thank you.

**Comment by johannesjo** [comment]
I think I found the source of this error. The fix will only apply to newly imported issues but not to old ones, unfortunately. Until the fix is out manually imported issues from the search input should have the correct link, but automatically to backlog imported once won't.

Thanks again! Let me know if you encounter any other issues.

**Comment by tustinn** [comment]
thanks, will give manual import a shot! thanks!!

**Comment by tustinn** [comment]
it worked, thanks!! :-)

**Comment by johannesjo** [comment]
Happy to hear that! Thanks for reporting back!
