### ISSUE TITLE
Feature Request: Record and allow editing time intervals

### ISSUE THREAD

**Issue by hackel** [johannesjo/super-productivity#59]
I'm really liking this app so far.  The one feature I miss from my current workflow (Currently using [TimeIT](https://github.com/Hoglet/TimeIT)) is the ability to see all of my recorded time intervals, and edit them/make corrections if necessary.  I'm not always the best at recording everything, and having this information helps me to piece together how my time was spent throughout the day, if I forgot to record something I did at a certain time, etc.

In terms of a UI, I would envision having an additional modal on the planner/work views (perhaps when clicking on the elapsed time, or a new icon) that shows a list of intervals.  You can then edit the start/stop time of any intervals, merge intervals, or delete intervals.  It would also be great to have a button to automatically convert an interval into a sub-task, or an option to move it to a different task.

The second view would be a daily view, similar to the daily agenda, but showing all of the time intervals from all projects throughout the day.  Clicking on any interval would show a modal with the same options described above.

I know this could be a bigger change, depending on how you're currently storing the time data, and might be more appropriate for version 2, but just wanted to get a conversation started!

**Comment by johannesjo** [comment]
Hey! Thanks for taking your time! I'm really glad that you like SP. 

Currently the app uses a simplified model for tracking time. It's not using intervals but just amounts of time you spent on different days (which you can edit by clicking on the clock icon). One of the reasons for that is to keep the data model smaller and faster and also to avoid several more or less complicated edge cases which would occur with other features of the app (such as the idle time dialog).

While I think I would prefer having time tracking like you described as it feels a little more accurate to me, the current model has also advantages regarding usability. It's much quicker to edit the time you spent on a particular task, as you don't have to deal with all those possibly tiny and fractured intervals. 

Maybe it would be possible to tackle your problem from another angle. Instead of using intervals directly on task level, it could be possible to save that data on another layer for the current session and last session and provide a option to quickly move that time to another task.
