### ISSUE TITLE
[Feature] Todoits integration

### ISSUE THREAD

**Issue by JakubHelis** [johannesjo/super-productivity#64]
Did you think about integrating this tool with todoist? It could be real killer! (right now it's hard for me to re-write tasks from Toodoist to this super tool ( ;) ). 
Even one-way integration could be great :) 

(It's my first comment / interaction with github so sorry if I made some mistake.
BTW: that app is awesome! )

**Comment by johannesjo** [comment]
Hey there! Thanks for taking your time to open up this issue. I never used Todoist myself. I like having more third party providers being integrated into super productivity, but it's always a big undertaking to do so. Especially because todoist seems to offer some features, which Super Productivity doesn't at the moment. The specific use case seems to be a little bit different too. While super productivity is aimed at a work context (especially software projects) offering you time sheet export and integration with the most common tools in this department, todoist seems more like a an all around tool.

Sooo for this to happen I need a lot more people wanting this feature OR you implement it yourself  via a Pull Request, which would be very welcome of course :)

**Comment by NinjaTurtle007** [comment]
+1 for todoist integration, it's one of the leading ones and even 1 way import could bring many new users to super productivity
ill be one of them

**Comment by zhjpwlj** [comment]
+1 for todoist integration or one-way importing

**Comment by H2O-Man** [comment]
+1 for one-way importing of Todoist tasks
