### ISSUE TITLE
Unpredictable application closure/crash (Linux)

### ISSUE THREAD

**Issue by IT-Tool** [johannesjo/super-productivity#678]
### Your Environment
* Version used: superProductivity_6.1.0_amd64.deb (installed for the first time).
* Operating System: Debian-based Parrot OS
* Desktop Environment: MATE 1.24.1

### Expected Behavior
if I enabled the option (in the settings) "Confirm before exiting the app" the app should not be closed without confirmation. But the fact is that the app crashes (without asking). I watched this for several days for now i cant identify why the app crashes.

### Current Behavior
When I work on a long task and I do not touch the app, it terminates invisibly.
By the way, i use only local projects.

### "Steps" to Reproduce (for bugs)
Applications are launched. I create projects/tasks. I turn on a timer. It counts the time. I close the tasks. Everything looks great!
But when I work on a long task and don't touch the application, it terminates unnoticeably. And I notice it too late to understand what preceded the crash.

### Console Output
Once launched the console and that's all it showed.
![202011192+](https://user-images.githubusercontent.com/53435741/99727721-50044580-2ab0-11eb-9fa0-afee75438dc6.png)
(Selected aria is when app crashed)

As more details become available, I will update this report (if needed). Thank You for free and Unique app!

### Error Log (Desktop only)
No log.log file

**Comment by johannesjo** [comment]
"getSettingsCb no callbacks left" is just a warning. What looks crucial is the "Segmentation fault". I'll have a look tomorrow. Until then could you maybe check if this is somehow helpful: #563

**Comment by thesignal** [comment]
**Your Environment**

    Version used: superProductivity_6.1.0_amd64.deb (installed over 6.0.1).
    Operating System: Debian 10 (buster)
    Desktop Environment: GNOME 3.30.2

Since I updated from 6.0.1 to 6.1.0 (.deb package) I'm experiencing the same issue - the application crashes with a segfault.

`journalctl | grep super`
`Nov 20 08:41:28 reactor kernel: superproductivi[28521]: segfault at 3abdcd4de000 ip 00007efbeb153175 sp 00007ffbffffa610 error 4 in libappindicator3.so.1.0.0[7efbeb14f000+5000]`

I'm also seeing some glitches in the UI, example below (but also had this in 6.0.1, not sure if this has anything to do with this issue)

![grafik](https://user-images.githubusercontent.com/892161/99763638-9f239800-2afb-11eb-98ac-509d4cc0c283.png)

**Comment by johannesjo** [comment]
Thanks @thesignal ! This might be due to a bug in the gnome-shell-appindicator extension.

Might make sense to roll back the custom indicator until this is fixed :(

https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1849142
ubuntu/gnome-shell-extension-appindicator#236

**Comment by squarebracket** [comment]
I just want to add I am also seeing the libappindicator segfault with the 6.1.0 snap on Fedora 32. I have a coredump if it's useful for you.

**Comment by IT-Tool** [comment]
> "getSettingsCb no callbacks left" is just a warning. What looks crucial is the "Segmentation fault". I'll have a look tomorrow. Until then could you maybe check if this is somehow helpful: #563 ?

This is not very useful because I don't use Gnome. And I can run and use app fine. It just crashes unexpectedly.

I found that we both don't have logs in the program folder. Why? How to enable it?

![2020-11-20](https://user-images.githubusercontent.com/53435741/99846038-894ebb00-2b6d-11eb-9c06-550b9960228a.gif)

**Comment by johannesjo** [comment]
I just made a new release which offers a startup flag `--disable-tray`. Could you maybe check if this resolves the issue?


> I found that we both (#563) don't have logs in the program folder. Why? How to enable it?
There is no need to enable them as they are enabled by default.

> This is not very useful because I don't use Gnome. And I can run and use app fine. It just crashes unexpectedly.
You're right. This does not rule out a relation completely however as they do share some packages such as libappindicator or some GLib stuff.

**Comment by IT-Tool** [comment]
> I just made a new release which offers a startup flag `--disable-tray`. Could you maybe check if this resolves the issue?

I checked the app at work only this evening. And I didn't notice any crashes yet. I need more 2 days. If it works stable for this days, I will close this ticket.

**Comment by johannesjo** [comment]
Thank you everybody!
