### ISSUE TITLE
The tray menu is glitchy (on Linux Mint XFCE)

### ISSUE THREAD

**Issue by IT-Tool** [johannesjo/super-productivity#680]
### Your Environment
* Version used: superProductivity_6.1.0_amd64.deb (installed for the first time).
* Operating System and version: Linux Mint 19.3
* Desktop Environment: XFCE

### Expected Behavior
After right-clicking on the program icon in the tray, the whole menu should be displayed at once.
![Screenshot_2020-11-20_16-21-51](https://user-images.githubusercontent.com/53435741/99826467-521de100-2b50-11eb-8a2e-1ab0c3838620.png)

### Current Behavior
![Screenshot_2020-11-20_16-21-20+](https://user-images.githubusercontent.com/53435741/99826504-5ba74900-2b50-11eb-941e-4ff4b3cc69db.png)
When you start moving the mouse cursor over the app menu (in tray), the buttons appear after second time moving mouse up and down.

### Steps to Reproduce
1. Run app,
2. Enable minimize to tray (in the settings),
3. Minimize app,
4. Pressing the right mouse button on tray icon.

**Comment by johannesjo** [comment]
Thanks for reporting. Likely not much we can do on super productivity's side of things but still good to know.

**Comment by IT-Tool** [comment]
Yes you're right this isn't just happening with super productivity.
If move XFCE panel back to the bottom of the screen the menu works without glitchy.

![Screencast-2020-11-20-](https://user-images.githubusercontent.com/53435741/99841964-e8f59800-2b66-11eb-9d2e-8ece3551a94b.gif)

**Comment by tuxflo** [comment]
Yeah the tray icon handling from electron in Linux is still far from good. For example it is not possible to simply show and hide the window using left click and show the menu on right click... I hope this will be fixed soon since there are a couple of electron based apps (not just super productivity) that lack such features. The issue where those things are addressed is: https://github.com/electron/electron/issues/14941
