### ISSUE TITLE
GitLab integration marks domains with .network as invalid

### ISSUE THREAD

**Issue by hashworks** [johannesjo/super-productivity#693]
### Your Environment
* Version used: [superproductivity-bin in the AUR](https://aur.archlinux.org/packages/superproductivity-bin/), uses DEB 6.1.1
* Operating System and version: Arch Linux
* Desktop Environment: i3wm

### Expected Behavior
I should be able to add a GitLab integration to `https://gitlab.foo.network/foo/bar`

### Current Behavior
Super Productivity marks the URL as invalid input.

### Steps to Reproduce (for bugs)
1. Try to add a GitLab integration to a domain with a `.network` TLD
2. Notice the invalid input message
3. Cry

### Screenshot
![example](https://fb.hash.works/KXtk2G8a/)

**Comment by johannesjo** [comment]
Still relevant possibly and PRs are welcome!

**Comment by webseppel** [comment]
I tried to reproduce this, but this issue seems to be fixed. 

I found the git URL is matched to this regex pattern which works with the mentioned URL `https://gitlab.foo.network/foo/bar`:

`/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)/`

Did I miss something?

**Comment by hashworks** [comment]
Yes, seems to be fixed.
