### ISSUE TITLE
Separate JIRA assignee username from JIRA login username (and password field deprecation)

### ISSUE THREAD

**Issue by RCI-LouisStAmour** [johannesjo/super-productivity#73]
It used to be that with password supported, JIRA would let me login with my assignee name (short username), but since JIRA's phasing out API access using passwords in favour of API token use, that access broke sometime last week (for me) and I had to switch from short username (first part of my company email address) to longer username (full username, as email address) to get the new API token to work in the password field. As a consequence, I'm seeing warnings that issues aren't assigned to me, because it's comparing against the longer email address form of username rather than the short assignee version. It would be nice to add an optional assignee field to allow overriding this. For the moment, I'm just ignoring the spurious issues.

Details on the deprecation: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

**Comment by RCI-LouisStAmour** [comment]
You might also want to insert a link to https://confluence.atlassian.com/cloud/api-tokens-938839638.html -- I keep having to google for that, as id.atlassian.com is not the first place I look for API tokens, and within the JIRA interface is a confusing OAuth API key page.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening up this issue. I've encountered the problem before, but didn't act so far, because I thought it would complicate several things and so far I hadn't had the need for an adjustment myself. But you're right. As the support is fading out, this needs to be addressed and providing an assignee field is a nice workaround for this problem, I haven't thought about myself.  

I probably won't have time for this for the next two weeks. But maybe you could provide a PR for the feature? I happily answer any question popping up along the way. :) Files you would want to look into are:
For the settings:
* `jira-settings-d.html`
* `constants.js`
For the logic:
`jira.s.js` and here the `taskIsUpdatedHandler` method

A link to the token page is already provided in the help section, though it might make sense to provide the information directly, as it is a bit safer to use the token, than to use the password directly (also something I probably should work on...).

**Comment by LouisStAmour** [comment]
I'll try to get to it, haven't had the time yet. 👍

**Comment by johannesjo** [comment]
No worries. 

I must admit that I feel a little sorry, for shamelessly trying to drag you into the project, but it could really use some more support ;)

**Comment by LouisStAmour** [comment]
I get it, and I agree I should contribute, that's how open source works :D 

But it's funny though, I often only think of this app when I've _other things_ to do! ;-)

**Comment by johannesjo** [comment]
I think I know what you mean. Working on this app is my favorite way to procrastinate (productively)  (:

**Comment by johannesjo** [comment]
So this took me quite a while, but this should be addressed now. In addition to the password it's also possible now to use the api token instead and there is an option now to provide a different assignee name.

**Comment by 45553907** [comment]
439129xxxxxxxxxx
