### ISSUE TITLE
Can't turn off the spelling checker

### ISSUE THREAD

**Issue by Rising-Soul** [johannesjo/super-productivity#751]
I looked around thoroughly in the options menu and I don't see any way to turn this off.

I searched both the issues section and the discussion area and didn't find anything mentioning the spelling checker.

### Your Environment

* Version used: 6.3.0-0 - AppImage
* Operating System and version: Manjaro Linux 20.1.1
* Desktop Environment: Xfce

**Comment by johannesjo** [comment]
Thanks for reporting. This is pretty interesting to me, because I never got spell checking to work in the first place with vanilla Ubuntu.

I'll try to have a look, though it might take a while, because I am pretty busy with other issues currently. 

Meanwhile PRs are welcome!

Here is some info on how to deal with the problem:
https://www.electronjs.org/docs/tutorial/spellchecker
