### ISSUE TITLE
Less clutter project view

### ISSUE THREAD

**Issue by mkpaz** [johannesjo/super-productivity#763]
## Problem Statement

1. There are several notions that are related to the project, but they are all located in different places:
    * Notes link is at the bottom of the sidebar and visible only when you are selected a project
    * Bookmarks link is in the content area topbar. There're additional problems with bookmarks. They're wider than tasks. If bookmarks list is collapsed there's no way to know if they're exist or not.
    * Metrics, Worklog, Settings links are in project related dropdown in sidebar
    * Backlog is shown inside collapsible area at the bottom of content area
    * There is also completed tasks which are right behind active tasks

2. Project content area has a huge vertical gaps and its content is somewhat misaligned.

    ![image](https://user-images.githubusercontent.com/25181998/103636323-3dac7100-4f63-11eb-94a6-28da4ab4869f.png)

## :grey_question: Possible Solution

In order to cleanup UI I'd propose:

1. Move time tracking info to the topbar. It's natural if this info would be located close to time tracking button. Also this move will free some vertical space, we could use for the tasks and notes.

    ![image](https://user-images.githubusercontent.com/25181998/103638271-20c56d00-4f66-11eb-8f2b-cab47dcaef45.png)

    Below the project title I'd be place project summary. How many current tasks, tasks in backlog, completed tasks etc. Just like icon + count. Sorry, I don't have enough photoshop skills to illustrate the idea :-) But if this proposal will get approval maybe I will try later.

2. Below the topbar show one of the following views: active tasks, backlog, completed tasks, notes, worklog, metrics, settings. 

    ![image](https://user-images.githubusercontent.com/25181998/103640174-fa550100-4f68-11eb-9cb8-311d4deac9d1.png)

    There could be 2 options to switch between these views (the second one is optional):
    * Dropdown button on the right side of project title (or on the left, if you don't have plans to support project icons). Button icon (see image above) should indicate current view. So if it's active tasks view you see task icon and so on.
    * Dropdown button on the right side of the project title in sidebar (just like now).

    Oh, and shortcuts of course.

    Dropdown menu
    
      ```
      Active tasks
      Backlog
      Completed tasks
      Notes
      ------------
      Worklog
      Metrics
      Settings
      ```

3. Convert Manage Projects button to the icon button on the right side of Create Project, like e.g. Microsoft ToDo did: This should clean up some vertical space in sidebar too. Also Manage Projects icon is pretty similar to the project icon

    ![image](https://user-images.githubusercontent.com/25181998/103640991-71d76000-4f6a-11eb-8575-b35402763ab5.png)

4. Do not show Finish Day button on the project page, because it's like... global. By clicking on it we're finishing the day not the project, so it should only be shown on Today page. 

Some thoughts about notes and bookmarks. These changes will require to reimplement how notes and bookmarks look and managed. Personally I think that notes and bookmarks is the same notion. Bookmark is just a note that contains only a link or an image. 

Pros:

- cleaner UI, more vertical space
- all project data in one place
- easier to implement some features (like search) in the future
- notes take full content area width, no need to use vertical slider anymore

Cons:

- Lots of work. Still I would be glad to help.

Ok, it was a lot of words but still just a rough sketch. To make final decisions it needs to start prototyping.

**Comment by johannesjo** [comment]
First of all: Thank you very much for this carefully crafted change request. I really appreciate it! I might have to think about the changes maybe some more, but I try to give some answers/feedback anyway. 

> 1. There are several notions that are related to the project, but they are all located in different places:

Makes a lot of sense to improve this!

> 2. Project content area has a huge vertical gaps and its content is somewhat misaligned.

I also agree!

> 1. Move time tracking info to the topbar. It's natural if this info would be located close to time tracking button. Also this move will free some vertical space, we could use for the tasks and notes.
>    ![image](https://user-images.githubusercontent.com/25181998/103638271-20c56d00-4f66-11eb-8f2b-cab47dcaef45.png)
>    Below the project title I'd be place project summary. How many current tasks, tasks in backlog, completed tasks etc. Just like icon + count. Sorry, I don't have enough photoshop skills to illustrate the idea :-) But if this proposal will get approval maybe I will try later.

It makes to me to move the stuff up. There are two things we need to account for however: 

1. The task title of the current task, which is shown until hovered and which would be over the three indicators
2. Small window sizes including the mobile app (possible we just hide or limit the information).

> 1. Below the topbar show one of the following views: active tasks, backlog, completed tasks, notes, worklog, metrics, settings.

I like having notes as a separate page. I am open but still not completely convinced about the backlog, as moving tasks via drag and drop is at least theoratically nice (though currently not very practical). I am not sure sure about the completed tasks, as having them in the same view (which will be what you're looking at most of the time) gives some sense of accomplisment and progress. It's probably not necessary to show them always in the planning view.

> 1. There could be 2 options to switch between these views (the second one is optional):
>
>    * Dropdown button on the right side of project title (or on the left, if you don't have plans to support project icons). Button icon (see image above) should indicate current view. So if it's active tasks view you see task icon and so on.
>    * Dropdown button on the right side of the project title in sidebar (just like now)
>
>    Oh, and shortcuts of course.
>    Dropdown menu
>
>    ```
>    Active tasks
>    Backlog
>    Completed tasks
>    Notes
>    ------------
>    Worklog
>    Metrics
>    Settings
>    ```

Makes sense to me!

> 1. Convert Manage Projects button to the icon button on the right side of Create Project, like e.g. Microsoft ToDo did: This should clean up some vertical space in sidebar too. Also Manage Projects icon is pretty similar to the project icon

I don't have strong feelings about this, but I would be ok with changing this.

> 1. Do not show Finish Day button on the project page, because it's like... global. By clicking on it we're finishing the day not the project, so it should only be shown on Today page.

Currently the finish day button  is not global (though it might make a lot more sense). Projects can be finished for the day separately, which also shows stuff like the evaluation form, which currently works on a project level. I plan to make this stuff global instead, but don't have an estimate when I get to this or how long it would take. 

> Some thoughts about notes and bookmarks. These changes will require to reimplement how notes and bookmarks look and managed. Personally I think that notes and bookmarks is the same notion. Bookmark is just a note that contains only a link or an image.

Bookmarks can also be commands, so they offer a bit more. I use them as quick access bar, as I usually have a couple of project specific urls I need to visit on a regular basis. I don't think we necessarily need to change how bookmarks work. Moving the option to show/hide the bookmark bar could be moved to the context menu. Otherwise I am personally fine with them. I might be also ok with removing them, too, but I am also a bit afraid about pissing people off who use them daily now :) 

The notes feature could use a complete revamp or maybe even be removed. In the very beginning there was just a single notepad per project, which might also be an option. The feature got a little bit more complicated, because I wanted to have little text bits visible most of the time, something like a PR checklist, a definition of done or just a motivational quote. Ideally the notes should move out of the menu and to the right again. But yeah, that's a big subject of its own :)

@papernoise as these are quite some big changes for the UI I'd really would love to hear your opinion about them!!

**Comment by mkpaz** [comment]
> Small window sizes including the mobile app (possible we just hide or limit the information).

Yes, I've checked this out too. It makes more sense to replace bookmark button with dropdown to switch between views (routes) then. We could also remove procrastination button from the main header and place it to the time tracking banner.

> The task title of the current task, which is shown until hovered and which would be over the three indicators

I'd vote to show currently active task as a banner. This way it won't override header bar and you could show full (or at least longer) task title.

> I like having notes as a separate page. I am open but still not completely convinced about the backlog, as moving tasks via drag and drop is at least theoratically nice (though currently not very practical). I am not sure sure about the completed tasks, as having them in the same view (which will be what you're looking at most of the time) gives some sense of accomplisment and progress. It's probably not necessary to show them always in the planning view.

Make a lot of sense, but I think it's hard to utilize planning view for both backlog and completed tasks. Placing backlog into bottom slider isn't very practical, because backlog can be quite big. So, it can placed right below undone tasks (it's where completed tasks now), but where to place completed tasks then? It's kind of trade-off. I like the idea to keep completed tasks in planning view, but I think it should be some toogle to show/hide them and maybe also a limit. Like only show last [30, 50, 100] completed tasks. 

> Currently the finish day button is not global (though it might make a lot more sense). 

Yeah, finish the day is the most confusing option for now I believe. Imho, it's pretty weird to see in project page, moreover it can be duplicated :-)

![image](https://user-images.githubusercontent.com/25181998/103758571-cabafd00-502b-11eb-86d6-8ffd30825ee4.png)

> Bookmarks can also be commands

Oh, I've missed that. It's definitely neat future. You're right, there's no sense to change DB, only UI need to be changed.

> The notes feature could use a complete revamp or maybe even be removed.

I use a separate note taking app, but I do like notes in GTD apps as well, usually to keep some projects related chunks of code like gists etc. I also like how they're combined with reminders in SP. E.g I use notes to remind me to make eye exercises twice a day. They're definitely could be useful for anyone.

**Comment by johannesjo** [comment]
> > Small window sizes including the mobile app (possible we just hide or limit the information).
>
> Yes, I've checked this out too. It makes more sense to replace bookmark button with dropdown to switch between views (routes) then. We could also remove procrastination button from the main header and place it to the time tracking banner.

Or even move it to the menu on the left side. It's not too essential for mobile I think.

> > The task title of the current task, which is shown until hovered and which would be over the three indicators
>
> I'd vote to show currently active task as a banner. This way it won't override header bar (cause it's actually the only location to place navigation buttons) and you could show full (or at least longer) task title. It could also open a possibility to dismiss that banner if user doesn't constant reminder what task he or she working on.

Using a banner won't work, as there effectively can only be one banner, which would block the spot most of the time for other messages, such as the break reminder, which is not good I think. So we need another solution. It's a tricky problem :) 

> Make a lot of sense, but I think it's hard to utilize planning view for both backlog and completed tasks. Placing backlog into bottom slider isn't very practical, because backlog can be quite big. So, it can placed right below undone tasks (it's where completed tasks now), but where to place completed tasks then? 

To have the backlog tasks always visible is not a good option I think. It might be better to allow showing them side by side or to give them their own special view. Btw. did you know that the backlog panel can be resized manually? You can grab it and pull it up all the way to the top. Maybe that's what should happen on click and the problem is solved for now?

> It's kind of trade-off. I like the idea to keep completed tasks in planning view, but I think it should be some toogle to show/hide them and maybe also a limit. Like only show last [30, 50, 100] completed tasks.

If a user uses "Finish day" (which is intended that they should) I can't see why there ever should be more than 30 or so done tasks. An option to hide them might be nice (or to sort tasks for that matter), but personally I am fine with how things are now.

> Yeah, finish the day is the most confusing option for now I believe. Imho, it's pretty weird to see in project page, moreover it can be duplicated :-)

For me it makes most sense to tackle this problem together for when the whole evaluation stuff is changed. So I'd suggest to discuss this as a topic of its own.

**Comment by mkpaz** [comment]
> Using a banner won't work, as there effectively can only be one banner, which would block the spot most of the time for other messages, such as the break reminder, which is not good I think. So we need another solution. It's a tricky problem 

Hmm, it won't take much place, just one persistent banner or something that looks like banner. There's also an option to implement separate time tracking widget, which would include everything: start/stop, button, counters, active task title etc and place it below the header bar, but I think banner is easier.

> You can grab it and pull it up all the way to the top. Maybe that's what should happen on click and the problem is solved for now?

Yeah, but because of overlay it still looks alien. Also the simpler layout the better I suppose. Horizontal switch hen maybe? I mean using angle icons button on the opposite sides of the subheader to switch between backlog and completed tasks. Probably should suit both mobile and desktop version.

```
- foo
- bar
- baz

< Backlog >

- john
- doe 
```

> An option to hide them might be nice (or to sort tasks for that matter)

I think the solution above covers this as well if default switch position is set to "Backlog". Also sorting function is another reason to free up the header bar, because I believe it's the natural place for the sorting button.

> For me it makes most sense to tackle this problem together for when the whole evaluation stuff is changed. So I'd suggest to discuss this as a topic of its own.

I agree with that, the more opinions the better, but I don't see people actively participate in discussions here. Either they happy with the current situation or don't care or both :-) Personally, I could live without finish day button entirely. My use case of SP is GTD app with time-tracking (pomodoro).

**Comment by johannesjo** [comment]
> Hmm, it won't take much place, just one persistent banner or something that looks like banner. There's also an option to implement separate time tracking widget, which would include everything: start/stop, button, counters, active task title etc and place it below the header bar, but I think banner is easier.

So you mean something like it is now, just positioned differently (e.g. below)? That could work though it still might overlap important bits of the UI sometimes.

> Horizontal switch hen maybe? I mean using angle icons button on the opposite sides of the subheader to switch between backlog and completed tasks. Probably should suit both mobile and desktop version.

A horizontal switch or overlay might be best, at least if we look at the problem isolated. It's probably a bit tricky to get right given all the stuff that is already going on. A separate page might also work, well. Hard to say without experimenting a little bit.

I am unsure what you mean by subheader. Could explain this a little bit more detailed?

**Comment by mkpaz** [comment]
Sure, I thought about that all morning. This is how I would do it for myself. Sorry for my photoshop skills :-)

![image](https://user-images.githubusercontent.com/25181998/103892235-aa12a600-5104-11eb-8582-51eb487f770b.png)

Also, I'm really sorry for bothering you will all the "ideas", hope you will maybe find something that make SP even better! But I have to stop using SP and stick to my previous task system until https://github.com/johannesjo/super-productivity/issues/771  is resolved. This feature kills me, sorry.

**Comment by johannesjo** [comment]
Thank you very much for your input once more. I am sure that it will be very useful once I find the time to improve the UI once more. I am not against switching things up to improve, but a major redesign just was done recently and there are other matters like the calendar integration in my focus for now. 

I am also glad that you found a solution that works for you now!

I must say however that I am a little surprised that 2 clicks each day once (which have the imho welcome side-effect that done tasks are gone from your list) is the main reason to make you want to switch apps.
