### ISSUE TITLE
Change issue handler

### ISSUE THREAD

**Issue by b0c1** [johannesjo/super-productivity#775]
## Problem Statement
If I change the issue tracker in the existing project (change another project or another tracker) all tasks wich linked to an issue id will be invalid. 

## :grey_question: Possible Solution
The task not only contains the issue id, but it must also contain the whole issue.
1. if the issue tracker change the task will contain the original issue (no problem)
2. when we want to update the issue we already own it
3. subtask can own the issue

**Comment by johannesjo** [comment]
Thanks for opening this up. You're right. This is something that isn't accounted for at all. I never encountered the problem myself while using the app, so I'd assume it's a little but of an edge case? Could you maybe describe a practical use case for  when this happens and is problematic?

I was saving all issue data in an earlier version, which was causing a lot of problems and increased complexity in several areas by quite a bit. I'd prefer not to go down that road again, if I am being honest.

**Comment by johannesjo** [comment]
ping @b0c1

**Comment by b0c1** [comment]
Hi,
First I think the issue tracker/project separation will solve the #783 issue. 
Second if the issue tracker project will be renamed/migrated/etc it still work.
I think the following solution can be work:
- issue tracker management separate from project
- so you separate handle the issue tracker configuration
- in the issue (not the project) will contain the issue tracker id and the issue id
- the project can be contain multiple issue tracker and the backlog will shown all issue wich assigned
- issue (or sub issue) can be bind to diferent issue tracker issue
- the issue can be contain not only the issue tracker and the issue tracker id but the downloaded issue tracker details for offline usage

I made some tests about storages and libraries. I think using localforage is a good idea and you can switch between indexeddb, websql or localstorage. With individual insert (each inserts wait for the previous) it's inserted 10k record 5.1s, with setinserts plugin it's 0.434s.

**Comment by johannesjo** [comment]
Thanks for getting back to me and your additional input on this!

> issue tracker management separate from project

This is still a bit unclear to me. Would they still be assigned to a project (yes?)? Or be globally available? Where are they managed and configured? How should the issue integrations be handled? What happens if one is deleted? And how should the add task bar work? 

> issue (or sub issue) can be bind to diferent issue tracker issue

Could you explain what you mean by that? You mean a tasks and sub tasks can be linked to any issue?

> the issue can be contain not only the issue tracker and the issue tracker id but the downloaded issue tracker details for offline usage

One advantage of the current solution is, that it is a bit easier to limit the amount of requests being sent at a time (auto adding issues to backlog is only checked for and done when a project is active for example). Even with a token Github and GItlab don't support an endless amount of requests. And there is no cache management, which is notoriously hard/error prone. And since syncing works with a complete data set, it's important to have the model as small as possible. To be clear: I am not saying that I am against making adjustments, but just that there are pros and cons to consider. Issue data was downloaded in a past version and I was pretty happy to get rid of it to be honest as it was causing all sorts of complications.

> I made some tests about storages and libraries. I think using localforage is a good idea and you can switch between indexeddb, websql or localstorage. With individual insert (each inserts wait for the previous) it's inserted 10k record 5.1s, with setinserts plugin it's 0.434s.

Super Productivity was using localforage at one point and for several reasons I decided to switch (in short: control, unfixed issues, overhead and it not being developed very actively anymore). Why would you want to change that and how is this related to the issue?

**Comment by b0c1** [comment]
I think separating the issue tracker and tasks is not a problem. Yes, I think issue tracker settings can be globally but can bind to project(s).
1. if the projects separated from the issue tracker you can define a custom filter/project so you can logically separate the issues in SP (super productivity). Why? Because you can separate by the priority, or the tags (for example FE and BE issues, etc) It's just an idea...
2. Yes I mean you can bind any issue tracker item to any task/subtask

> One advantage of the current solution is, that it is a bit easier to limit the number of requests being sent at a time (auto adding issues to the backlog is only checked for and done when a project is active for example). 

I disagree... I mean I just "cache" the fetched data from the search. (You got the title/state/create/updated/closed states, labels, assignees, author etc).. You already have this data when you fetch the issues. You already can be updated each issue in the local cache on each search it's not a plus request just a regular X min issue search when checking the new issues...

> Why would you want to change that and how is this related to the issue?

It's related because I think issue tracker issues need to be cached, so I think to cache the issues and refresh when you search the new issues. You persist for the backlog or the tasks.

It's just an idea...
