### ISSUE TITLE
Tags for subtasks

### ISSUE THREAD

**Issue by itsamirrezah** [johannesjo/super-productivity#794]
Hello, 

I'd like to be able to tag my sub task as well as my main one, unfortunately it hasn't been possible yet.
I think this feature will give you more flexibility to design your projects/tasks.

Thank you for your hard work

**Comment by johannesjo** [comment]
Hello there! Thanks for the suggestion. The choice is intentional because this would open up a lot of followup problems in terms of logic and ui wise, such as was happens if a parent get's a tag and what to list for the tag lists, how to communicate that sub tasks of sub tasks are not possible and a couple more.
