### ISSUE TITLE
Migration from TSLint to ESLint

### ISSUE THREAD

**Issue by undrivendev** [johannesjo/super-productivity#803]
## Problem Statement
This project uses TSLint, but it's deprecated. You can see the deprecation notice when you run `npm run lint`. See here for more information: https://github.com/palantir/tslint/blob/master/README.md

## :grey_question: Possible Solution
TSLint should be replaced with ESLint. See here for the official migration path: https://github.com/angular-eslint/angular-eslint#migrating-from-codelyzer-and-tslint

## :heavy_plus_sign: Additional context
It should also be considered that it's not guaranteed that the same exact linting behaviour is maintained after the migration, there could be some differences, but it's probably a necessary one to do nonetheless.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. This is on my radar but recently I am just swamped with other issues and the new calendar feature. Any chance you might want to give it a shot yourself @undrivendev ? :)

**Comment by undrivendev** [comment]
Hi! Sure thing, I'll give it a shot ;)

**Comment by johannesjo** [comment]
That's great news! Let me know, if you have any questions. I hope things go smoothly. Those things are either surprisingly easy or a pain in the ***. :)

**Comment by undrivendev** [comment]
Hi Johannes, I have performed the migration and pushed the changes on my fork: https://github.com/undrivendev/super-productivity/commit/f4ef0e2047ca5afc5b9987fc4c92932621d694dd 
The linter is working on my machine but the problem is that I get now a lot of errors, and by a lot I mean thousands. I made a list of the eslint rules that are failing (see below). I think we have a couple of options here:
1. Downgrade the failing rules from error level to warnings, info or even ignore them all together
2. fix them all automatically (I don't think it's a good idea)
3. Mix of both: ignore or downgrade the less important/most impactful ones and fix the ones that makes the most sense.
What do you think?

Here are the failing rules:
```
@typescript-eslint/member-ordering
@typescript-eslint/no-inferrable-types
no-underscore-dangle
@typescript-eslint/member-delimiter-style
no-shadow
@typescript-eslint/naming-convention
arrow-body-style
@angular-eslint/component-selector
@typescript-eslint/ban-types
@angular-eslint/no-input-rename
@typescript-eslint/no-unused-expressions
prefer-arrow/prefer-arrow-functions
@angular-eslint/directive-selector
prefer-const
max-len
id-blacklist
```

**Comment by johannesjo** [comment]
Hey there! That's cool that you are already that far. I made a comment on every item about what I personally would prefer, which isn't to say that I let myself be convinced that another option would be preferable :) In general I would say: Let's be pragmatic. If something is just nice to have but requires 100+ non trivial changes, then it is probably not worth to go down that road (at least for now).

@typescript-eslint/member-ordering
=> disable it, because custom order might be more useful(logical)

@typescript-eslint/no-inferrable-types
=> disable it, if it's not a quick fix

no-underscore-dangle
=> disable it, because currently all private variables got this and I think it is useful this way

@typescript-eslint/member-delimiter-style
=> keep it, if it doesn't require too many changes

no-shadow
=> keep it, if it doesn't require too many changes

@typescript-eslint/naming-convention
=> keep it, if it doesn't require too many changes, might require some finetuning
I personally would prefer these styles, which should be present mostly throughout the app.
```
const SOME_GLBOAL_EXPORTED_CONFIG_CONST => we need some flexibilty;
const someNormalVariable;
let someNormalVariable;
public blaBabla
private _blaBla;
class ClassName;
```
  

arrow-body-style
=> disable it

@angular-eslint/component-selector
=> disable it, if it's not a quick fix

@typescript-eslint/ban-types
=> keep it, if the default is reasonable and if it doesn't require too many changes

@angular-eslint/no-input-rename
=> disable it, because this is sometimes useful together with setters/getters

@typescript-eslint/no-unused-expressions
=> keep it, if it doesn't require too many changes

prefer-arrow/prefer-arrow-functions
=> keep it, if it doesn't require too many changes

@angular-eslint/directive-selector
=> keep it, if it doesn't require too many changes

prefer-const
=> keep it, if it doesn't require too many changes

max-len
=> keep it, if it doesn't require too many changes, I am also ok with a bit more than the standard 80. maybe something like 150?

id-blacklist
=> keep it, if it doesn't require too many changes

**Comment by undrivendev** [comment]
Hey!
So, if you look at my branch commits: https://github.com/undrivendev/super-productivity/commits/feat/803_eslintmigration you can see I've disabled the rules causing errors and removed the references to tslint.
If you agree, I'd like to complete do a PR for the migration and, after that, I can help you re-enable the ESLint rules that you said you'd like to keep (and I agree on those). That's because I'd like to create a separate PR for every rule because the fix of each one of them will impact multiple files. I'd prefer to have multiple small PRs instead of a big one.
What do you think?

**Comment by johannesjo** [comment]
Hey @undrivendev makes sense to me to split this up, but at the same time I also would like to keep the master branch clean, because I might need to make a patch release in the next couple of days to deal with google drive sync not working any more. How about I create an intermediate branch like temporary develop branch?

**Comment by undrivendev** [comment]
Sounds good to me! ;)

**Comment by johannesjo** [comment]
Alright :) the branch should be there now.

**Comment by undrivendev** [comment]
The ESLint migration has been merged into master with the problematic rules aforementioned set to disabled. I am proceeding to re enable them gradually and fix the errors that arise along the way.
