### ISSUE TITLE
Sort Git* issues (e.g., by issue number)

### ISSUE THREAD

**Issue by sdruskat** [johannesjo/super-productivity#839]
First up, sorry for putting in yet another enhancement suggestion without offering to work on it myself. If ever I can find some spare time to work on more OS projects, this one is the one I'd love to contribute to.

## Problem Statement

When importing issues from GitLab/Hub, the issues in the task list are not orderable. This makes it hard sometimes to find the issue you want to work on, especially when the list is long. Some basic ordering would be nice, e.g., to be set in the project settings for GitHub/-Lab. The one that comes to mind is order by issue number, which would already help immensely.

## :grey_question: Possible Solution

Create an option in project settings to sort by issue number, (as compared to "as they come").

## :arrow_heading_up: Describe alternatives you've considered

-

## :heavy_plus_sign: Additional context

-

**Comment by johannesjo** [comment]
Hi there! No worries! Improvement suggestions are always welcome. I agree that some sort of sorting would be nice, but I'd assume that tasks should be sortable (e.g. by title or by creation date and maybe by issue id) rather than just thew new issues coming in. Would you agree or did I maybe misunderstand your suggestion and you are just talking about the case, when there are multiple issues imported at once?
