### ISSUE TITLE
Web-app will not render on iOS Safari

### ISSUE THREAD

**Issue by cjimison** [johannesjo/super-productivity#87]
## Your Environment

* Version used: Web App at https://super-productivity.com/app/#!/
* Operating System and version: iOS 11.4
* Device: iPhone 7+
* Browser Name and version: Safari

## Expected Behavior
I can see something rendered on my screen

## Current Behavior
When I try to go to the webapp version of super-productivity on my iOS device using Safari I just get a blank white screen.  LOVE the app and would like to use it on my phone as well.

## Steps to Reproduce (for bugs)
https://super-productivity.com/app/#!/

1. Open the above URL on an iOS device
2. Observer blank white screen 

## Question:

Are you guys considering adding a donations page to your main site?  I would love to support super-productivity's continued development and frankly cash is cheaper than time :smiley:

**Comment by johannesjo** [comment]
Hey there! I will check Safari as soon as I can. I'm currently on vacation, so this might take a while. :) 

Currently there is no such thing as a donation page. I have to think about it.

**Comment by johannesjo** [comment]
Hey there! I suppose it should be running now at least. You'll probably encounter more issues. To be honest: I never really checked mobile Safari, because this started out as a electron app where you are free from it and all its quirks and so far I thought that nobody uses the mobile version.

I also thought about the donations thing. I really would like to spend more time on the app, but even bigger projects hardly make any money with donations and it's complicated with the taxes for such things in Germany. Maybe I put up some link to a charity I like or something like that.

For now it is already super cool if you report bugs and other usability issues. Helps a lot, too!
