### ISSUE TITLE
file:/// links not working when setting project background image

### ISSUE THREAD

**Issue by aspieln3r** [johannesjo/super-productivity#875]
### Your Environment

* Version used: web version
* Operating System : linux
* Browser Name and version: chromium 88

### Expected Behavior

entering file:///home/user/picture.jpg to project bg image url sets picture.jpg as background image
### Current Behavior

when setting project background, if I use file:///home/user/picture.jpg, its not getting set as background. It works fine with http links but image loading is slow as there seem to be no local caching of images

### Steps to Reproduce (for bugs)

Use a valid file url for setting project background image
### Console Output

`Not allowed to load local resource: file:///home/user/picture.jpg`

**Comment by johannesjo** [comment]
Yes this is not possible for the web version as browsers don't allow for this.

**Comment by aspieln3r** [comment]
Feature request: cache images locally. 
When entering an image url, everytime I open a project, it takes a while to load the image(not only the first time). I think this could be solved by caching the image locally. what do you think

**Comment by roboyoshi** [comment]
I was about to reopen this, because it was not very intuitive to set the background to a file. I discovered the "change background" option by accidentally clicking on the project page. But the modal did not allow for files to be used (local app, not web). I figured out how to set it eventually, but here are a few remarks on that:

- Right-Click on the Background shows a "Change Background" option, yet it only allows for a user to use unsplash images.
- Using a `file://` url in that dialog does not work.
- Instead the user needs to go to the `3-dots-menu` at the top and choose `Settings` for that project and set a `file://` url for the light/dark options.
- I think it would be nice to have a `file://` or `upload` or at least a `remote-url (https://)` option directly in the modal that is shows when using the "change background" button on the project site directly.
- It would also be nice to have a global option, but I guess this becomes part of themes eventually (those appear to be in beta right now)

**Demo Project - Right Clicking the Site**
<img width="942" height="417" alt="Image" src="https://github.com/user-attachments/assets/3dae86fc-8c98-4527-b253-cd69fe00109e" />

**Selecting the Background here only allows Unsplash**
<img width="975" height="655" alt="Image" src="https://github.com/user-attachments/assets/0d9b0915-909b-44ec-9554-e3213387e365" />

**Where to go instead**
<img width="347" height="377" alt="Image" src="https://github.com/user-attachments/assets/7103774c-afc0-4b53-afe3-71e5dc833cb0" />

**Settings for background**
<img width="1020" height="827" alt="Image" src="https://github.com/user-attachments/assets/e48a0b67-f225-45b4-a424-f7f76c329697" />

**Comment by johannesjo** [comment]
> I was about to reopen this, because it was not very intuitive to set the background to a file. I discovered the "change background" option by accidentally clicking on the project page. But the modal did not allow for files to be used (local app, not web). I figured out how to set it eventually, but here are a few remarks on that:

This is very old. Let's open up a new issue about this.
