### ISSUE TITLE
Nextcloud Syncing Conflict

### ISSUE THREAD

**Issue by GammaPi** [johannesjo/super-productivity#912]
I recently deployed super-productivity on my server and try to sync it with my nextcloud server.

However, I found after local content change. Super-productivity will always report "both local and remote content are modified." And I have to click "from local" button every time.

I tried to analyze the source code. The root cause is:

In

https://github.com/johannesjo/super-productivity/blob/013e6579f05cc600cd14e72cc046af69ad121440/src/app/imex/sync/web-dav/web-dav-sync.service.ts#L96

and

https://github.com/johannesjo/super-productivity/blob/013e6579f05cc600cd14e72cc046af69ad121440/src/app/imex/sync/sync-provider.service.ts#L242

The app uses r.headers.etag as request successful indicator. If this value is null. Then the app will throw an error.

And in

https://github.com/johannesjo/super-productivity/blob/03ff2fb0086225b9b56832e308b2751e2afc0f52/src/app/imex/sync/sync-provider.service.ts#L244

https://github.com/johannesjo/super-productivity/blob/03ff2fb0086225b9b56832e308b2751e2afc0f52/src/app/imex/sync/sync-provider.service.ts#L203

The app won't update last sync date if there's an error. And that makes last sync date different from local file date. This will cause the problem.

**Comment by GammaPi** [comment]
Etag now appears. I will reopen if this problem still exists. But I encountered this problem last time.

**Comment by GammaPi** [comment]
Have to reopen this. The problem still exists. Last time the problem was solved by my fix.

**Comment by GammaPi** [comment]
The missing etag is caused by the webdav library used.
I tried to manually "etag" on nginx, but the output tells me there's no etag.

**Comment by GammaPi** [comment]
I can see my custom "etag" on nginx response log. But the console printout of return object shows no such header.

**Comment by GammaPi** [comment]
I currently return "success" rather than etag in header to avoid the null problem.


```javascript
  async uploadAppData(data: AppDataComplete, localRev: string, isForceOverwrite: boolean = false): Promise<s
tring | Error> {
    this._globalProgressBarService.countUp(T.GPB.WEB_DAV_UPLOAD);
    try {
      const r = await this._webDavApiService.upload({
        data,
        localRev,
        isForceOverwrite
      });
      console.log(r);
      this._globalProgressBarService.countDown();
      
      return "success";
    } catch (e) {
      console.error(e);
      this._globalProgressBarService.countDown();
      return e;
    }
  }
}

```

**Comment by GammaPi** [comment]
If I enable etag on Linux. Nextcloud will return "oc-etag" rather than "etag".
However, as I mentioned above. Even if I can see this in the network request tab. The console output of request object still has no "oc-etag" in return value.

![image](https://user-images.githubusercontent.com/19838874/108626824-39a7b600-7420-11eb-8e6a-192a7604183a.png)

**Comment by GammaPi** [comment]
@johannesjo

**Comment by johannesjo** [comment]
Hi there! The missing etag looks like a problem with your server configuration. It's maybe best to address this to the maintainers of nextlcoud?

**Comment by janLo** [comment]
The problem is most likely due to header restrictions in CORS - you're not allowed to access headers that are not explicitly whitelisted by the server in the preflight-request. See https://github.com/nextcloud/server/issues/3131 for more details. You can use the mentioned app https://apps.nextcloud.com/apps/webapppassword as a workaround if you're the administrator of your NC instance.

**Comment by GammaPi** [comment]
@janLo I handled preflight request correctly. The webdav actually works (It's able to upload files to nextcloud).
The problem is, Super Productivity thinks the upload has failed.

@johannesjo If super productivity can successfully handle oc-etag, the problem is fixed. However, when I see oc-etag from network tab in browser debugger, super productivity reports there's no oc-etag.

**Comment by johannesjo** [comment]
> @johannesjo If super productivity can successfully handle oc-etag, the problem is fixed. However, currently even if I enable oc-etag in nginx and can see this header from browser debugger. Super productivity reports there's no oc-etag (I checked the console log).

The question is, if the oc-etag shows up under the network tab. If it does, it's just a quick fix on SPs side of things. If it doesn't it's likely a server config issue.

**Comment by janLo** [comment]
Webdav depends on proper etags for a lot of things: https://tools.ietf.org/html/rfc4918#section-8.6. If they'te not working that its probably not an issue on the SP-side.I just checked on my instance. I get the `oc-etag` and the `etag` header back. If you [digg a bit in the history](https://doc.owncloud.org/server/8.1/admin_manual/whats_new_admin.html) you'll see, that the `oc-etag` only was a Workaround in the first place:
    Introduce new “OC-ETag” header fixing issues with server configs stripping off ETags “No E-Tag received from server”

Also notice that the etag-header is only sent in the `PUT` and `GET` requests. The `PROPFIND` requests provide the etag value within the XML-response. Generally the etag is necessary to check if a entity has changed on the server. If the etag-header is missing or not useable in your responses then it has most likely two reasons:
* Something between you and Nextcloud is stripping it away (most likely your reverse proxy or another proxy on the way)
* The same-origin-foo forbids you to use this header because its not explicitly allowed.

The fist can happen on nginx for example if you use the `gzip_proxied` option without the `no_etag` flag.

The CORS mechanism is described in https://fetch.spec.whatwg.org/#http-access-control-allow-headers and explained in more details here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

For a simple solution to same-origin/CORS related issues you can use the [Webapppassword](https://apps.nextcloud.com/apps/webapppassword) app mentioned above.

Using the non-standard oc-etag here should be the last resort as its most likely a server configuration problem you're mitigating with this.

**Comment by GammaPi** [comment]
Thanks janLo for the information.
I checked again and find etag and oc-etag both appear in nginx. Previously, I didn't add "etag on" to my nginx config. And I tried to override etag header manually. After I add etag on, I forgot to remove that custom etag. So the working configuration looks like this:

```
location /remote.php {


        proxy_pass ....;
        proxy_buffering off;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-Ssl     on;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;

        etag on;  # After adding this, both etag and oc-etag header appears in the debugger.

        add_header 'Access-Control-Allow-Origin' '*' always;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' '*' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
            add_header 'Access-Control-Max-Age' 3600 always;
            add_header 'Content-Length' 0 always;
            add_header 'Content-Type' 'text/plain; charset=utf-8' always;
            return 200;
        }


    }

```
## Log from browser debugger network tab.

```
# Request

PUT WEB_DAV_ADDR HTTP/2
Host: NEXTCLOUD_SERVER
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://tracker.xttech.top/
Content-Type: application/octet-stream
Authorization: Basic PRIVATE
Content-Length: 42268
Origin: SP_SERVER
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
TE: Trailers

#Response

HTTP/2 204 No Content
server: nginx
date: Wed, 24 Feb 2021 12:04:18 GMT
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
x-powered-by: PHP/7.4.14
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: PRIVATE
oc_sessionPassphrase=PRIVATE
__Host-nc_sameSiteCookielax=PRIVATE
__Host-nc_sameSiteCookiestrict=PRIVATE
content-security-policy: default-src 'none';
x-hash-sha256: PRIVATE
x-hash-sha1: PRIVATE
x-hash-md5: PRIVATE
oc-fileid: 04207860oc6aa5mjrhl9
etag: "6059c2c0a7ab960b7528500a88b705f7"
oc-etag: "6059c2c0a7ab960b7528500a88b705f7"
access-control-allow-origin: *
X-Firefox-Spdy: h2

```

## Output from console
I believe the following output is printed out by:

https://github.com/johannesjo/super-productivity/blob/013e6579f05cc600cd14e72cc046af69ad121440/src/app/imex/sync/web-dav/web-dav-sync.service.ts#L94

```
{
  "data": "",
  "status": 204,
  "statusText": "No Content",
  "headers": {
    "cache-control": "no-store, no-cache, must-revalidate",
    "expires": "Thu, 19 Nov 1981 08:52:00 GMT",
    "pragma": "no-cache"
  },
  "config": {
    "url": "WEBDAV URL",
    "method": "put",
    "data": "{PRIVATE}
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/octet-stream",
      "Content-Length": 42268,
      "Authorization": "Basic PRIVATE"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1
  },
  "request": {}
}
```

**Comment by janLo** [comment]
The `etag on` should not make a difference here as it enables the automatic etag generation for static content: http://nginx.org/en/docs/http/ngx_http_core_module.html#etag

What you need is to tell nginx to not change the etag header coming from the PHP side. I recommend the nextxloud example nginx config. This should cover most of the issues. It can be found here: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

**Comment by GammaPi** [comment]
Yeah. But as my previous comments is just to show even if etag is normal Super productivity sill fail to realize it's existence.

**Comment by janLo** [comment]
If thats the case that you've probably a worngly configured allowed-headers CORS Header. 

Looking at your configuration from above: teh Wildcard `"*"` will brobably not work in this case because your request is NOT unauthorized:

    For requests **without credentials**, the literal value "*" can be specified, as a wildcard; the value tells browsers to allow requesting code from any origin to access the resource. **Attempting to use the wildcard with credentials will result in an error**.

(See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin). 

The purpose of CORS is to provide explicit exceptions to the same-origin policy. These should be as specific as possible to prevent your browser from leaking sensitive information via malicious javascript.

I therefore still suspect a misconfiguration of your webserver. I recommend to use the default Nginx-Config from above and the mentioned NC-App if you're not 100% sure what the several options imply.

It works for me without any problems btw.

**Comment by GammaPi** [comment]
Thanks for the information.

**Comment by johannesjo** [comment]
@janLo thank you very for digging into this and helping out. Would you advice against using the oc-etag as fallback? It should be a simple change to two or three lines of code after all.

**Comment by janLo** [comment]
I don't know if it's worth it. It's not a standard header, only owncloud/nextxloud support it, it still needs to be explicitly allowed via cors. I think if someone has the ability (admin access) to configure cors for the oc-etag they can fix the etag configuration.

**Comment by johannesjo** [comment]
Makes a lot of sense! Thank you! I am closing this then.

**Comment by GammaPi** [comment]
It's kind of interesting.
Super productivity can upload to nextcloud successfully.
I can see etag from debugger.
Etag is missing from super productivity output.
From my understanding, if that's a CORS issue, then the upload won't be successful and network request will have error in the first place (I won't see successful request in debugger).

**Comment by GammaPi** [comment]
Thanks janLo for your guidance. I finally used webapppassword  to set CORS rather than manually configure nginx.
I guess I need to learn more about CORS before using a customized config.
