### ISSUE TITLE
New tasks added at the botton in "Today" view

### ISSUE THREAD

**Issue by plamkas** [johannesjo/super-productivity#920]
I am not sure if there is a specific reason for this but I've noticed that new tasks added in the "Today" view via the shortcut Shift+A appear at the top instead at the bottom. If a new task is added within a project it will appear at the bottom which for me is an expected behaviour, since chances are that the oldest tasks will to be processed next.

**Comment by johannesjo** [comment]
Hi there! Makes somehow sense now that you say it. Maybe we should make it configurable as well, so people can use whatever they prefer.

**Comment by sroener** [comment]
Hi,

I didn't find this config in the options section. I think this is still relevant and would be a very convenient solution.

**Comment by bytrangle** [comment]
I thought one can use `Ctrl + 2` to toggle between adding a new task to the bottom versus top? So this is no longer an issue, unless you're still open to make it configurable?

But adding new tasks is always a situational thing. Sometimes you want the task to be located different from what you configure globally. So in the end, you still need the shortcut for toggling.

**Comment by sroener** [comment]
I can see that point, but would it be possible that the last setting is remembered between sessions?

 I just tested it by toggling with `Ctrl + 2`, but the next time the program is started, it resets to the default.

**Comment by sroener** [comment]
@bytrangle Thank you for the extensive answer. 

Yes, my preference would be adding tasks to the bottom and moving them around, if they have a higher priority. 

I would agree that users should not be forced to do it one way or the other. In my opinion option 1 would work well.

Another option to consider, would be a feature where the program remembers the state of where to add the next task. This way, people can change the way how tasks are added intuitively without going to the preferences. If a user has a strict preference for adding tasks at the bottom, they just have to toggle it once instead of every session.

**Comment by johannesjo** [comment]
I also think option 1 is the best, as this might confuse existing users otherwise. PRs are welcome! :)

**Comment by frainz-de** [comment]
Yes, the issue is still relevant for me.

**Comment by rsmyst** [comment]
I would like if the Ctrl+2 setting actually saved in between task additions. I doubt it's *too* hard to code in too. i like putting higher priority tasks higher on the list so newer tasks tend to go to the bottom.

**Comment by johannesjo** [comment]
@rsmyst yes that seems like the most sensible path to choose. PRs are welcome!
