### ISSUE TITLE
Link to sponsorship page from contributing section and contributing.md

### ISSUE THREAD

**Issue by menelic** [johannesjo/super-productivity#925]
Thank you for a great, well thought out tool that combines great UX with a thoughtful integration of tips and nudges towards healthy habits. I suggest you add a link to the sponsorship option in the contributing section and in contributing.md ! 

Allow me to ask - since you have merged #889 which would allow me to advocate for super productivity to be used and possibly sponsored at my workplace - when are you planning the next release?  Since you reacted positively to #914: Implementing this would definitely drive up adoption further....

An aside regading a slightly different use case: Have you ever considered creating a kind of dashboard where a project lead could see overall times spent on projects and tasks in a team where Super Productivty is used for time tracking by several contributors?

**Comment by johannesjo** [comment]
Hi @menelic ! Thanks for the suggestion!

 > An aside regading a slightly different use case: Have you ever considered creating a kind of dashboard where a project lead could see overall times spent on projects and tasks in a team where Super Productivity is used for time tracking by several contributors?

Yes I definitely have thought about this and there even have been some requests about it in the past with people wanting to pay actual money for this :D 

So far I haven't found the time to dig deeper into this, but it's definitely something I'd like to explore. I would need a lot of input though, because while I am pretty well aware of what my personal time tracking needs are and maybe even what might be those of other digital workers, I am lacking all the knowledge when it comes to what companies of different sizes would need.

Maybe we can have a chat about it sometime? You can contact me via email: contact@super-productivity.com
