### ISSUE TITLE
Repeating task improvements (reminders, monthly tasks and specific times) (Repeat tasks, repeat tasks)

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#948]
I think the basic goal should be to achieve a functionality like google calendar or Thunderbird offer for reoccurring events. 

It should be possible to:
1. Select several week days similar to how it is now.
2. To create monthly tasks.
3. ~~To either have an "all-day task" (just shows up on the list) or to specify a specific time (shows up with a reminder).~~ done

Imho less important, but maybe also nice to have would be
1. Biweekly or triweekly (is this a word?? :D)  tasks
2. Yearly tasks
3. Re-creating sub tasks  (as optional feature)
4. Even more funky re-creation patterns

Still unclear to me is (lacking a good concept):
1. How to deal with the task creation or in other words when exactly should a task show up in its list and how to deal with all it's future instances?
2. Should task meta data such as the description be the same among all instances per default? 
3. In what way to create sub tasks. Probably a simple solution is best, that just uses the title (maybe with the short syntax included) but ignores everything else. I'd like to keep things as simple as possible for this.

EDIT: It would be cool if you add a thumps add to the original issue, so I can get a rough picture on how strong the demand is for this.

**Comment by surli** [comment]
Hi I was just about to create a feature request about repeating task when I found this. 
I'm personally using the repeating tasks for my daily routine tasks (I have for example a task for repeated stuff I do in the morning, and for monitoring the average time I spent on answering on our company's chat). So on my side the main problem I'm encountering is that except the "morning routine" I never really close those tasks since I'm using them through the all day, and I often forgot to close them at the end of the day, so it happens a lot that I got twice the same task appearing the following day. 

I assume it's related to what you mention:
> How to deal with the task creation or in other words when exactly should a task show up in its list and how to deal with all it's future instances?

So I guess we can imagine different possibilities:
  - tasks might be auto-closeable at the end of the repetition period 
  - maybe some tasks are in fact never closed so it's always the same instance appearing (could be useful in my case since the "Answer on chat" task is not something I expect to really close one day)

Hope it's the right place to share those thoughts, let me know if you prefer that I create a feature request for this - maybe - quite specific need :)

**Comment by johannesjo** [comment]
@surli thanks for your input! That definitely makes sense!

**Comment by MAX10541** [comment]
I currently use a GNOME plugin called [time++](https://github.com/zagortenay333/timepp__gnome) that has several features similar to Super Productivity.
Regarding repeating tasks, they support a specific syntax like "3d" (repeat every 3 days) and "x-3d" (repeat 3 days **after completing**), among other things.

See the last section in this table, it might give you some ideas: [https://github.com/zagortenay333/timepp__gnome#todotxt-extensions](https://github.com/zagortenay333/timepp__gnome#todotxt-extensions).

**Comment by johannesjo** [comment]
As a first step it is now possible to specify a start time for repeating tasks.

**Comment by daya** [comment]
Is it possible to have a more granular repeating option i.e. every few hours. My use case being medication reminders

**Comment by johannesjo** [comment]
@daya this won't work well with how repeating tasks are designed, but for stuff like this there is this issue #446

**Comment by MAX10541** [comment]
Another thing I would like to address (probably not entirely related to this thread) is how the existing instance of a repeating task is handled when a new instance is created. Right now, the older instance (i.e. task) is marked as "completed" even if the user didn't actually complete it.  

For example:
I have a repeating tasks about reading some book. I don't always read that book, and some sometimes I might finish the day without completing that task. The next day, when I open SupProd, and the new task are being created, the task from the previous day still shows up, but will be marked as completed. A new task will be created instead.  


I would suggest to mark the old task as something other than "completed". Maybe "archived" instead? same goes to how it's saved in the backups (I can see it has `"isDone": true` and `"doneOn"` timestamp) and internally.

Why am I suggesting this? because I have some custom jupyter notebooks to analyze my work behavior, and marking these repeating tasks as completed even thought they are not is messing up my analysis.

**Comment by johannesjo** [comment]
> The next day, when I open SupProd, and the new task are being created, the task from the previous day still shows up, but will be marked as completed. A new task will be created instead.

The idea behind this is, that much of the literature on productivity suggests to mark your tasks as done at the end of the day (but transfer it to the next days list if it isn't of course). 

Not sure how your analyse looks like, but maybe you can delete the task instead and/or use tags??

**Comment by MAX10541** [comment]
@johannesjo Thank you for the clarification. Here are a couple more follow up questions, just to make sure I fully understand this 100%:  
1. Are these completed tasks included in the exports? and in the metrics and worklog?
2. If yes, why? I didn't complete these tasks, or even do any work towards them, so it doesn't really make sense to include them.

I really appreciate your time :)

**Comment by johannesjo** [comment]
> * Are these completed tasks included in the exports? and in the metrics and worklog?

Done tasks are, deleted tasks are not.

> * If yes, why? I didn't complete these tasks, or even do any work towards them, so it doesn't really make sense to include them.

Because of what I mentioned above and in order to keep things simpler.

**Comment by MAX10541** [comment]
I've opened [this new feature request](https://github.com/johannesjo/super-productivity/issues/1459).  

Thank you again for all your efforts!

**Comment by tuaone** [comment]
hello admin.
I don't see a repeat every month, every year
![no](https://user-images.githubusercontent.com/59154355/131218448-e1237654-d3b3-4ccc-861f-b8d6ac8db116.JPG)

**Comment by Jayy001** [comment]
![image](https://user-images.githubusercontent.com/56607897/140192652-3c0bfbc1-d610-4dcd-938c-32689707901f.png)
How do I add the repeating tasks? I dont see an advanced menu anywhere

**Comment by johannesjo** [comment]
@Jayy001 please go to the [discussions page](https://github.com/johannesjo/super-productivity/discussions) for questions like this.

**Comment by johannesjo** [comment]
Most of the stuff has been implemented and should be available for testing on the edge channel shortly.

**Comment by frainz-de** [comment]
I'd still like to see the recurring subtasks feature

**Comment by ashutoshsaboo** [comment]
Not stale

**Comment by ashutoshsaboo** [comment]
still relevant

**Comment by KatrinIhler** [comment]
Something that I would really like to see in regards to the scheduling of recurring tasks, but which I suspect might be a little more involved, is something like "first/second/... \<weekday\> of the month", so for example "last Wednesday of the month". We have quite a number of meetings in our Community which are scheduled this way and it saddens me that I can't use recurring tasks for them. .__.

**Comment by johannesjo** [comment]
I am closing this in favor of separate new issues like:
#2471 
#2752
#2938 

If you find anything is missing, please create a new issue and reference this one.
