### ISSUE TITLE
Allow projects to have default tags for created tasks

### ISSUE THREAD

**Issue by Rodeo-McCabe** [johannesjo/super-productivity#986]
## Problem Statement

Certain projects I have fit within the scope of a tag, and I want to be able to track the tasks with that tag too. For example I have a project "Front Yard Stairs", which is under the tag "Yard work". Right now I have to edit the tag of each task as I make it (or use the `#` syntax which is very helpful). However it would be convenient if in the project settings I could specify default tags to be added automatically when I make a new task.

## :heavy_plus_sign: Additional context
#972 I think the suggestion here is also a solution, so long as projects use the same tags tasks do.

**Comment by johannesjo** [comment]
Hi there! Thanks for the suggestion. I like it! Pull Requests would be welcome for this.

**Comment by topoescobar** [comment]
A very necessary implementation for the use that I give to the app, I like to separate all the projects into large categories, (study, work and hobbies) and in general a project always has the same label.

**Comment by darius-r** [comment]
Any chance of this being revived? It doesn't seem to exist yet. 

It would also help solve the problem of there being no 'view all tasks' list. Having this would allow us to add something like an '#all' tag to every project, which would result in every nested task receiving this. In turn giving a defacto view that lists every single task in one view.

**Comment by johannesjo** [comment]
This should be now possible with the automations plugin.

**Comment by darius-r** [comment]
> This should be now possible with the automations plugin.

Confirmed to be working! 

I'm using the tag '#all' to give myself a list of every task in one place. 

The automation looks like this for anyone trying it. Note that you should pre-create the tag before creating the automation. 
When typing into the 'Action', include the # sign before the tag.  
Trigger: taskCreated
Conditions: no condition
Action: addTag: #all    

The above automatically adds the referenced tag to every new task. 

I did this on the Android app in a matter of seconds. 

If anyone doss try this, you should heed the warning about using the automations. It necessarily doesn't have the guard rails you might otherwise be use to when interacting with an app :)
