### ISSUE TITLE
The LEFT vertical bar can be restored just upon resizing the window app

### ISSUE THREAD

**Issue by giammi56** [johannesjo/super-productivity#993]
### Environment
* Version used: latest snap 6.5.2
* Operating System and version: Ubuntu 20.04.2 with GNOME

### procedure to recreate the behaviour
Maximize the window app, press/hold ESC multiple times, the LEFT lateral bar collapse laterally. There is no way to call it back. 

### expected behaviour
There should be a shortcut, the proximity of the cursor or a button to restore the LEFT vertical bar. Resizing the window two times (i.e. maximize and minimise) restores the LEFT bar. 

### Console Output
Pressing ESC with the console open  doesn't let the LEFT vertical bar collapsing.

**Comment by johannesjo** [comment]
Thanks for opening this up. I have a hard time to understand what t he problem is here. At a certain size the left menu is always shown, since there is always more than enough space. Is that it?

**Comment by giammi56** [comment]
I have edited the post. Just a remark: pressing ESC makes the left bar collapsing **most of the time**, but not always. I am wondering if there is a timeout for it to collapse automatically (doesn't seem to) or what triggers the collapsing. The RIGHT bar works like a charm pressing the right arrow when a task is selected.

**Comment by johannesjo** [comment]
Ahh ok! Thanks for the explanation. I think I got it now. The behavior is like this: The side nav is only closed by the ESC key if it has keyboard focus. If you think this should be different: The best place to address this, is probably the angular/material library as the component is taken from there.

Otherwise I recommend using the keyboard shortcut for showing/hiding the side nav, which should always work.
